#!/bin/sh

# Create default Hyperion build directory, if it does not exist.
# Then configure using the arguments.

# Your current working directory MUST be the one where this file resides
# DO NOT source this script.

dodir () {
if [ ! -d $1 ] ; then
        mkdir $1
        if [ $? -ne 0 ] ; then
                echo "Cannot create directory '$1'.  Terminating."
                exit 12
        fi
        echo "Created '$1'." >&2
else
        echo "'$1' exists." >&2

fi
}

where=$PWD
build=../$(uname -m)/hyperion
dodir ../$(uname -m)
dodir $build

cd $build
$where/configure "$@"
