/*----------------------------------------------------------------------------*/
/* (c) Copyright Roger Bowler and others 1999-2010                            */
/* Hercules-390 mainframe emulator                                            */
/*                                                                            */
/* file: msgenu.h                                                             */
/*                                                                            */
/* (c) Copyright Bernard van der Helm 2010                                    */
/* Main header file for Hercules messages.                                    */
/*----------------------------------------------------------------------------*/

#define MSG(id, ...)      #id " " id "\n", ## __VA_ARGS__
#define WRITEMSG(id, ...) logmsg(#id " " id "\n", ## __VA_ARGS__)

/* awstape.c */
#define HHCTA101I "Device(%4.4X): AWS Tape file(%s) closed"
#define HHCTA102E "Device(%4.4X): Error opening file(%s): (%s)"
#define HHCTA103E "Device(%4.4X): Error seeking to offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA104E "Device(%4.4X): Error reading block header at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA105E "Device(%4.4X): End of file (end of tape) at offset("I64_FMTX") in file(%s)"
#define HHCTA106E "Device(%4.4X): Unexpected end of file in block header at offset("I64_FMTX") in file(%s)"
#define HHCTA107E "Device(%4.4X): Block length(%d) exceeds at offset("I64_FMTX") in file(%s)"
#define HHCTA108E "Device(%4.4X): Invalid tapemark at offset("I64_FMTX") in file(%s)"
#define HHCTA109E "Device(%4.4X): Error reading data block at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA110E "Device(%4.4X): Unexpected end of file in data block at offset("I64_FMTX") in file(%s)"
#define HHCTA111E "Device(%4.4X): Error seeking to offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA112E "Device(%4.4X): Media full condition reached at offset("I64_FMTX") in file(%s)"
#define HHCTA113E "Device(%4.4X): Error writing block header at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA114E "Device(%4.4X): Media full condition reached at offset("I64_FMTX") in file(%s)"
#define HHCTA115E "Device(%4.4X): Error writing data block at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA116E "Device(%4.4X): Error writing data block at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA117E "Device(%4.4X): Error seeking to offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA118E "Device(%4.4X): Error writing block header at offset("I64_FMTX") in file (%s): (%s)"
#define HHCTA119E "Device(%4.4X): Error writing tape mark at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA120E "Device(%4.4X): Sync error on file(%s): (%s)"

/* bldcfg.c */
#define HHCCF001S "Error reading file(%s) line(%d): (%s)"
#define HHCCF002S "File(%s) line(%d) is too long"
#define HHCCF003S "Open error file(%s): (%s)"
#define HHCCF004S "No device records in file(%s)"
#define HHCCF008E "Error in file(%s) line(%d): Syntax error:(%s)"
#define HHCCF009E "Error in file(%s) line(%d): Incorrect number of operands"
#define HHCCF012S "Error in file(%s) line(%d): (%s) is not a valid CPU (%s)"
#define HHCCF013S "Error in file(%s) line(%d): Invalid main storage size (%s)"
#define HHCCF014S "Error in file(%s) line(%d): Invalid expanded storage size (%s)"
#define HHCCF016S "Error in file(%s) line(%d): Invalid (%s) thread priority (%s)"
#define HHCCF017W "Hercules is not running as setuid root, cannot raise (%s) thread priority"
#define HHCCF018S "Error in file(%s) line(%d): Invalid number of CPUs (%s)"
#define HHCCF019S "Error in file(%s) line(%d): Invalid number of VFs (%s)"
#define HHCCF020W "Vector Facility support not configured"
#define HHCCF022S "Error in file(%s) line(%d): (%s) is not a valid system epoch. The only valid values are 1801-2099"
#define HHCCF023S "Error in file(%s) line(%d): (%s) is not a valid timezone offset"
#define HHCCF029S "Error in file(%s) line(%d): Invalid SHRDPORT port number (%s)"
#define HHCCF031S "Cannot obtain (%d)MB main storage: (%s)"
#define HHCCF032S "Cannot obtain storage key array: (%s)"
#define HHCCF033S "Cannot obtain (%d)MB expanded storage: (%s)"
#define HHCCF034W "Expanded storage support not installed"
#define HHCCF035S "Error in file(%s) line(%d): Missing device number or device type"
#define HHCCF036S "Error in file(%s) line(%d): (%s) is not a valid device number(s) specification"
#define HHCCF051S "Error in file(%s) line(%d): (%s) is not a valid serial number"
#define HHCCF052W "Warning in file(%s) line(%d): Invalid ECPSVM level value: (%s), 20 Assumed"
#define HHCCF053W "Error in file(%s) line(%d): Invalid ECPSVM keyword: (%s), NO Assumed"
#define HHCCF061W "Warning in file(%s) line(%d): (%s) statement deprecated. Use (%s) instead"
#define HHCCF062W "Warning in file(%s) line(%d): Missing ECPSVM level value, 20 Assumed"
#define HHCCF063W "Warning in file(%s) line(%d): Specifying ECPSVM level directly is deprecated. Use the 'LEVEL' keyword instead"
#define HHCCF064W "Hercules set priority (%d) failed: (%s)"
#define HHCCF065I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCCF070S "Error in file(%s) line(%d): (%s) is not a valid year offset"
#define HHCCF072W "SYSEPOCH (%04d) is deprecated, please specify \"SYSEPOCH 1900 (%s%d)\""
#define HHCCF073W "SYSEPOCH (%04d) is deprecated, please specify \"SYSEPOCH 1960 (%s%d)\""
#define HHCCF074S "Error in file(%s) line(%d): Invalid engine syntax (%s)"
#define HHCCF075S "Error in file(%s) line(%d): Invalid engine type (%s)"
#define HHCCF077I "Engine (%d) set to type (%d) (%s)"
#define HHCCF081I "File(%s) will ignore include errors"
#define HHCCF082S "Error in file(%s) line(%d): Maximum nesting level (%d) reached"
#define HHCCF083I "File(%s) including(%s) at (%d)"
#define HHCCF084W "File(%s) open error ignored file(%s): (%s)"
#define HHCCF085S "File(%s) open error file(%s): (%s)"
#define HHCCF086S "Error in file(%s): NUMCPU(%d) must not exceed MAXCPU(%d)"
#define HHCCF090I "Default Allowed AUTOMOUNT directory = (%s)"
#define HHCCF900S "Out of memory"

/* cache.c */
#define HHCCH001E "Calloc failed cache[%d] size(%d): (%s)"
#define HHCCH002W "Realloc increase failed cache[%d] size(%d): (%s)"
#define HHCCH003W "Realloc decrease failed cache[%d] size(%d): (%s)"
#define HHCCH004W "Buf calloc failed cache[%d] size(%d): (%s)"
#define HHCCH005W "Releasing inactive buffer space"
#define HHCCH006E "Unable to calloc buf cache[%d] size(%d): (%s)"

/* cardpch.c */
#define HHCPU004E "Error writing to file(%s): (%s)"
#define HHCPU001E "File name missing or invalid"
#define HHCPU002E "Invalid argument: (%s)"
#define HHCPU003E "Error opening file(%s): (%s)"

/* cardrdr.c */
#define HHCRD001E "Out of memory"
#define HHCRD002E "File name(%s) too long, max is (%ud)"
#define HHCRD003E "Unable to access file(%s): (%s)"
#define HHCRD004E "Out of memory"
#define HHCRD005E "Specify 'ascii' or 'ebcdic' (or neither) but not both"
#define HHCRD006E "Only one filename (sock_spec) allowed for socket devices"
#define HHCRD007I "Defaulting to 'ascii' for socket device(%4.4X)"
#define HHCRD008W "'multifile' option ignored: only one file specified"
#define HHCRD009E "File name(%s) too long, max is (%ud)"
#define HHCRD010E "Unable to access file(%s): (%s)"
#define HHCRD011E "Close error on file(%s): (%s)"
#define HHCRD012I "%s (%s) disconnected from device(%4.4X) (%s)"
#define HHCRD013E "Error opening file(%s): (%s)"
#define HHCRD014E "Error reading file(%s): (%s)"
#define HHCRD015E "Seek error in file(%s): (%s)"
#define HHCRD016E "Error reading file(%s): (%s)"
#define HHCRD017E "Unexpected end of file(%s)"
#define HHCRD018E "Error reading file(%s): (%s)"
#define HHCRD019E "Card image exceeds (%d) bytes in file(%s)"

/* cckddasd.c */
#define HHCCD001I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCCD002I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCCD003I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCCD011I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCCD012I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCCD013I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCCD092I "%d devices processed"
#define HHCCD101E "%4.4X error initializing shadow files"
#define HHCCD102E "%4.4X file[%d] get space error, size exceeds %lldM"
#define HHCCD110E "%4.4X file[%d] devhdr id error"
#define HHCCD121E "%4.4X file[%d] trklen err for %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD122E "%4.4X file[%d] invalid byte 0 trk %d: buf %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD123E "%4.4X file[%d] invalid byte 0 blkgrp %d: buf %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD124E "%4.4X file[%d] invalid %s hdr %s %d: %s compression unsupported"
#define HHCCD125E "%4.4X file[%d] invalid %s hdr %s %d buf %p:%2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD130E "%4.4X file[%d] %s open error: %s"
#define HHCCD131E "%4.4X file[%d] close error: %s"
#define HHCCD132E "%4.4X file[%d] lseek error, offset 0x%" I64_FMT "x: %s"
#define HHCCD133E "%4.4X file[%d] read error, offset 0x%" I64_FMT "x: %s"
#define HHCCD134E "%4.4X file[%d] read incomplete, offset 0x%" I64_FMT "x: read %d expected %d"
#define HHCCD135E "%4.4X file[%d] lseek error, offset 0x%" I64_FMT "x: %s"
#define HHCCD136E "%4.4X file[%d] write error, offset 0x%" I64_FMT "x: %s"
#define HHCCD137E "%4.4X file[%d] write incomplete, offset 0x%" I64_FMT "x: wrote %d expected %d"
#define HHCCD138E "%4.4X file[%d] ftruncate error, offset 0x%" I64_FMT "x: %s"
#define HHCCD139E "%4.4X malloc error, size %d: %s"
#define HHCCD140E "%4.4X calloc error, size %d: %s"
#define HHCCD142E "%4.4X file[%d] shadow file name %s collides with %4.4X file[%d] name %s"
#define HHCCD151E "%4.4X file[%d] error re-opening %s readonly: %s"
#define HHCCD160E "%4.4X not a cckd device"
#define HHCCD161E "%4.4X file[%d] no shadow file name"
#define HHCCD162E "%4.4X file[%d] max shadow files exceeded"
#define HHCCD163E "%4.4X file[%d] error adding shadow file"
#define HHCCD164I "%4.4X file[%d] %s added"
#define HHCCD165W "%4.4X error adding shadow file, sf command busy on device"
#define HHCCD170E "%4.4X not a cckd device"
#define HHCCD171E "%4.4X file[%d] cannot remove base file"
#define HHCCD172E "%4.4X file[%d] not merged, file[%d] cannot be opened read-write%s"
#define HHCCD173E "%4.4X file[%d] not merged, file[%d] check failed"
#define HHCCD174E "%4.4X file[%d] not merged, file[%d] not hardened"
#define HHCCD175W "%4.4X file[%d] merge failed, sf command busy on device"
#define HHCCD179I "Merging device %d:%4.4X"
#define HHCCD180E "%4.4X file[%d] not merged, error during merge"
#define HHCCD181I "%4.4X shadow file [%d] successfully %s"
#define HHCCD182E "%4.4X file[%d] not merged, error processing trk %d"
#define HHCCD190E "%4.4X file[%d] offset 0x%" I64_FMT "x unknown space: %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD193E "%4.4X file[%d] uncompress error trk %d: %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD194E "%4.4X file[%d] %s compression not supported"
#define HHCCD200I "Compressing device %d:%4.4X"
#define HHCCD201I "Checking device %d:%4.4X level %d"
#define HHCCD202W "%4.4X file[%d] check failed, sf command busy on device"
#define HHCCD205W "%4.4X device is not a cckd device"
#define HHCCD206W "%4.4X file[%d] compress failed, sf command busy on device"
#define HHCCD207I "Adding device %d:%4.4X"
#define HHCCD208I "Displaying device %d:%4.4X"
#define HHCCD209W "%4.4X device is not a cckd device"
#define HHCCD210I "          size free  nbr st   reads  writes l2reads    hits switches"
#define HHCCD211I "                                                 readaheads   misses"
#define HHCCD212I "--------------------------------------------------------------------"
#define HHCCD213I "[*] %10" I64_FMT "d %3" I64_FMT "d%% %4d    %7d %7d %7d %7d  %7d"
#define HHCCD214I "                                                    %7d  %7d"
#define HHCCD215I "%s"
#define HHCCD216I "[0] %10" I64_FMT "d %3" I64_FMT "d%% %4d %s %7d %7d %7d"
#define HHCCD217I "%s"
#define HHCCD218I "[%d] %10" I64_FMT "d %3" I64_FMT "d%% %4d %s %7d %7d %7d"
#define HHCCD900I "print_itrace"

/* console.c */
#define HHCGI001I "Unable to determine IP address from (%s)"
#define HHCGI002I "Unable to determine port number from (%s)"
#define HHCGI003E "Invalid parameter: (%s)"

#define HHCTE001I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCTE002W "Waiting for port(%u) to become free"
#define HHCTE003I "Waiting for console connection on port(%u)"
#define HHCTE004I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s)" 
#define HHCTE005E "Cannot create console thread: (%s)"
#define HHCTE007I "Device(%4.4X): Devtype(%4.4X) client(%s) connection closed"
#define HHCTE008I "Device(%4.4X): Connection closed by client(%s)"
#define HHCTE009I "Client(%s) connected to device(%d:%4.4X) devtype(%4.4X)"
#define HHCTE010E "CNSLPORT statement invalid: (%s)"
#define HHCTE011E "Device(%4.4X): Invalid IP address: (%s)"
#define HHCTE012E "Device(%4.4X): Invalid mask value: (%s)"
#define HHCTE013E "Device(%4.4X): Extraneous argument(s): (%s)..."
#define HHCTE014I "Device(%4.4X): Devtype(%4.4X) client(%s) connection reset"
#define HHCTE017E "Device(%4.4X): Duplicate SYSG console definition"
#define HHCTE090E "Device(%4.4X): Malloc() failed for resume buf: (%s)"

/* cpu.c */
#define HHCCP001W "%s%02X thread set priority(%d) failed: (%s)"
#define HHCCP002I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s%02X)"
#define HHCCP003I "%s%02X architecture mode(%s)"
#define HHCCP004I "%s%02X Vector Facility online"
#define HHCCP006S "Cannot create timer thread: (%s)"
#define HHCCP007I "%s%02X architecture mode set to (%s)"
#define HHCCP008I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s%02X)"
#define HHCCP010I "%s%02X store status completed"
#define HHCCP011I "%s%02X disabled wait state(%s)"
#define HHCCP014I "%s%s%s%02X: (%s) code(%4.4X) ilc(%d%s)"
#define HHCCP015I "%s%02X PER event: code(%4.4X) perc(%2.2X) addr(" F_VADR ")"
#define HHCCP016I "%s%02X: Program interrupt loop: PSW(%s)"
#define HHCCP022I "Machine Check code (%16.16" I64_FMT "u)"
#define HHCCP043I "Wait state PSW loaded: (%s)"
#define HHCCP044I "I/O interrupt code(%4.4X) CSW(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X)"
#define HHCCP045I "I/O interrupt code(%8.8X) parm(%8.8X)"
#define HHCCP046I "I/O interrupt code(%8.8X0 parm(%8.8X), id(%8.8X)"
#define HHCCP080E "%s%02X malloc failed for archjmp regs: (%s)"

/* crypto/dyncrypt.c */
#define HHCRY001I "Crypto module loaded (c) Copyright Bernard van der Helm, 2003-2010"
#define HHCRY002I "  Active: %s"

/* hao.c */
#define HHCIN004S "Cannot create HAO thread: (%s)"
#define HHCAO001I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCAO002I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCAO003I "Firing command: (%s)"
#define HHCAO004I "The defined Automatic Operator rule(s) are:"
#define HHCAO005I "(%02d): (%s) -> (%s)"
#define HHCAO006I "(%d) rule(s) displayed"
#define HHCAO007E "Unknown hao command, valid commands are:\n" \
                  "          hao tgt <tgt> : define target rule (pattern) to react on\n" \
                  "          hao cmd <cmd> : define command for previously defined rule\n" \
                  "          hao list <n>  : list all rules/commands or only at index <n>\n" \
                  "          hao del <n>   : delete the rule at index <n>\n" \
                  "          hao clear     : delete all rules (stops automatic operator)"
#define HHCAO008E "No rule defined at index(%d)"
#define HHCAO009E "Invalid index, index must be between 0 and (%d)"
#define HHCAO010E "Target not added, table full"
#define HHCAO011E "Tgt command given, but cmd command expected"
#define HHCAO012E "Empty target specified"
#define HHCAO013E "Target not added, duplicate found in table"
#define HHCAO014E "%s"
#define HHCAO015E "%s"
#define HHCAO016I "Target placed at index(%d)"
#define HHCAO017E "Cmd command given, but tgt command expected"
#define HHCAO018E "Empty command specified"
#define HHCAO019E "Command not added; causes loop with target at index(%d)"
#define HHCAO020I "Command placed at index(%d)"
#define HHCAO021E "Target not added, causes loop with command at index(%d)"
#define HHCAO022I "All automatic operation rules cleared"
#define HHCAO023E "Hao del command given without a valid index"
#define HHCAO024E "Rule at index(%d) not deleted, already empty"
#define HHCAO025I "Rule at index(%d) succesfully deleted"
#define HHCA0026E "Command not added, may cause dead locks"

/* hdl.c */
#define HHCHD001E "Registration malloc failed for (%s)"
#define HHCHD005E "Module(%s) already loaded\n"
#define HHCHD006S "Cannot allocate memory for DLL descriptor: (%s)"
#define HHCHD007E "Unable to open DLL(%s): (%s)"
#define HHCHD008E "Device(%4.4X) bound to (%s)"
#define HHCHD009E "Module(%s) not found"
#define HHCHD010I "Dependency check failed for (%s), version(%s) expected(%s)"
#define HHCHD011I "Dependency check failed for (%s), size(%d) expected(%d)"
#define HHCHD013E "No dependency section in (%s): (%s)"
#define HHCHD014E "Dependency check failed for module(%s)"
#define HHCHD015E "Unloading of module(%s) not allowed"
#define HHCHD016E "DLL(%s) is duplicate of (%s)"
#define HHCHD017E "Unload of module(%s) rejected by final section"
#define HHCHD018I "Loadable module directory is (%s)"
#define HHCHD900I "Begin shutdown sequence"
#define HHCHD901I "Calling (%s)"
#define HHCHD902I "(%s) complete"
#define HHCHD909I "Shutdown sequence complete"
#define HHCHD950I "Begin HDL termination sequence"
#define HHCHD951I "Calling module(%s) cleanup routine"
#define HHCHD952I "Module(%s) cleanup complete"
#define HHCHD959I "HDL Termination sequence complete"

/* hostinfo.c */
#define HHCIN015I "%s"

/* httpserv.c */
#define HHCHT001I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCHT002E "Socket error: (%s)"
#define HHCHT003W "Waiting for port(%u) to become free"
#define HHCHT004E "Bind error: (%s)"
#define HHCHT005E "Listen error: (%s)"
#define HHCHT006I "Waiting for HTTP requests on port(%u)"
#define HHCHT007E "Select error: (%s)"
#define HHCHT008E "Accept error: (%s)"
#define HHCHT009I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCHT010E "Http_request create_thread error: (%s)"
#define HHCHT011E "Html_include: Cannot open file(%s): (%s)"
#define HHCHT013I "Using HTTPROOT directory (%s)"
#define HHCCF066E "Invalid HTTPROOT: (%s): (%s)"

/* panel.c */
#define HHCPN001I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCPN002S "Cannot obtain keyboard buffer: (%s)"
#define HHCPN003S "Cannot obtain message buffer: (%s)"

/* timer.c */
#define HHCTT001W "Timer thread set priority(%d) failed: (%s)"
#define HHCTT002I "Thread started tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"
#define HHCTT003I "Thread ended tid(" TIDPAT "), pid(%d), prio(%d), name(%s)"

/* version.c */
#define HHCIN010I "%sversion (%s)"
#define HHCIN011I "%s"
#define HHCIN012I "Built on (%s) at (%s)"
#define HHCIN013I "Build information:"
#define HHCIN014I "  %s"
