/* MSGENU.H     (c) Copyright Bernard van der Helm, 2010             */
/*              Header file for Hercules messages (US English)       */

/* Message text (c) Copyright Roger Bowler and others, 1999-2010     */

// $Id$ 

/*-------------------------------------------------------------------*/
/* This file contains the text of all of the messages issued by      */
/* the various components of the Hercules mainframe emulator.        */
/*-------------------------------------------------------------------*/

/*-------------------------------------------------------------------
Message principles:
-----------------------------------------------------------------------
HMMMnnnns Text

-----------------------------------------------------------------------
Prefix principles
-----------------------------------------------------------------------
H:    'H' is the standard prefix for all Hercules messages.
MMM:  Three capital letter module code, related to the module.
nnnn: Four numeric digit code that unifies the Hercules message.
s:    The capital letter that denotes the severity.
' ':  One space character between the message prefix and Text.

-----------------------------------------------------------------------
Severity principles
-----------------------------------------------------------------------
S: Severe error, this could terminate Hercules.
E: Error, hercules continues.
W: Warning message.
I: Informatonal message.
A: Action, Hercules needs input.
D: Debug message.

-----------------------------------------------------------------------
Text principles
-----------------------------------------------------------------------
Text: 
1. The text is written in lower characters and starts with a 
   capital and does not end with a '.', '!' or something else.
2. Added strings are rounded with apostrophes to delimiter it from
   the text and to see the start and endpoint of the string.

Examples:
"HABC1234I This is a correct message"
"HBCD2345E This is wrong!"
"HCDE3456E THIS IS ALSO WRONG"
"HDEF4567E Do not end with a dot or somehting else!"
"HEFG5678E This string %s cannot be seen and is therefore wrong", ""
"HFGH6789I This is a '%s' better example", "much"

-----------------------------------------------------------------------
Message format principles:
-----------------------------------------------------------------------
Device:     "%1d:%04X", lcssnum, devnum
Processor:  "%s%02X", PTYPSTR(procnum), procnum
32bit reg:  "%08X", r32
64bit reg:  "%016X", r64 (in 64bit mode)
64bit reg:  "--------%08X", r32 (under SIE in 32 bit)
64bit psw:  "%016X", psw64
64bit psw:  "%016X ----------------", psw32 (under SIE in 32 bit)
128bit psw: '%016X %016X", psw64h, psw64l
Regs:       "GR%02d CR%02d AR%02d FP%02d", grnum, crnum, arnum, fpnum
Strings:    '%s', ""
-----------------------------------------------------------------------
DEBUG
-----------------------------------------------------------------------
If DEBUG is defined, either by #define or configure --enable-debug
and OPTION_DEBUG_MESSAGES is enabled in featall.h then messages
will be prefixed by sourcefile.c:lineno: where the message originates
cpu.c:123:HABC1234I This is a message
-----------------------------------------------------------------------
Module codes:
CSH cache.c
RDR cardrdr.c
PUN cardpch.c
SRV service.c
---------------------------------------------------------------------*/

#define MSG(id, ...)      #id " " id "\n", ## __VA_ARGS__
#define MSG_C(id, ...)      #id " " id "", ## __VA_ARGS__
#define WRITEMSG(id, ...) writemsg(__FILE__, __LINE__, sysblk.msglvl, "", _(#id " " id "\n"), ## __VA_ARGS__)
#define WRITECMSG(color, id, ...) writemsg(__FILE__, __LINE__, sysblk.msglvl, color, _(#id " " id "\n"), ## __VA_ARGS__)  

/* Hercules messages */

/* cache.c */
#define HCSH0001E "Function '%s' failed; cache '%d' size '%d': '[%02d] %s'"
#define HCSH0002W "Function '%s' failed; cache '%d' size '%d': '[%02d] %s'"
#define HCSH0003W "Function '%s' failed; cache '%d' size '%d': '[%02d] %s'\n          Releasing inactive buffer storage"

/* cardpch.c */
#define HPUN0001E "%1d:%04X File '%s': name too long, maximum length is '%ud'"
#define HPUN0002E "%1d:%04X Invalid argument: '%s'"
#define HPUN0003E "%1d:%04X File '%s': %s error: '[%02d] %s'"
#define HPUN0004E "%1d:%04X File name is missing"

/* cardrdr.c */
#define HRDR0001E "%1d:%04X Out of memory"
#define HRDR0002E "%1d:%04X File '%s': name too long, maximum length is '%ud'"
#define HRDR0003E "%1d:%04X File '%s': %s error: '[%02d] %s'"
#define HRDR0004E "%1d:%04X Out of memory"
#define HRDR0005E "%1d:%04X Options 'ascii' and 'ebcdic' are mutually exclusive"
#define HRDR0006E "%1d:%04X Only one filename (sock_spec) allowed for socket device"
#define HRDR0007I "%1d:%04X Option 'ascii' is default for socket device"
#define HRDR0008W "%1d:%04X Option 'multifile' ignored: only one file specified"
#define HRDR0012I "%1d:%04X IPv4 Address: %s (%s) disconnected from device (%s)"
#define HRDR0017E "%1d:%04X File '%s': Unexpected end of file"
#define HRDR0019E "%1d:%04X File '%s': Card image exceeds '%d' bytes"

/* service.c */
/* SRV0001 is more readable without the quotes */
#define HSRV0001I "%s"
#define HSRV0002E "SCP not receiving '%s'"
#define HSRV0003E "Empty SCP command issued"
#define HSRV0004I "Control program information: type '%s', name '%s', sysplex '%s', level %16.16"I64_FMT"X"
#define HSRV0005W "The configuration has been placed into a system check-stop state because of an incompatible service call"
#define HSRV0006I "SYSCONS interface '%s'"
#define HSRV0007I "%s%02X Vector Facility configured '%s'"

/*
 *                                  N E W   M E S S A G E   F O R M A T
 *=========================================================================================================================================
 *                                  O L D   M E S S A G E   F O R M A T
 */
 
/* awstape.c faketape.c omatape.c */ 
#define HHCTA101I "%1d:%04X Tape file '%s': '%s' tape closed"
#define HHCTA107E "%1d:%04X Tape file '%s': block length %d exceeds maximum at offset "I64_FMTX
#define HHCTA108E "%1d:%04X Tape file '%s': invalid tapemark at offset "I64_FMTX
#define HHCTA121E "%1d:%04X Tape file '%s': error in function '%s', offset "I64_FMTX": '%s'"
#define HHCTA122E "%1d:%04X Tape file '%s': error in function '%s': '%s'"

/* omatape.c - TDF file processing */
#define HHCTA232I "%1d:%04X TDF File '%s': invalid filename: TDF files must be in the TAPES subdirectory"
#define HHCTA239E "%1d:%04X TDF File '%s': open error: '%s'"
#define HHCTA240E "%1d:%04X TDF File '%s': function fstat() error: '%s'"
#define HHCTA241E "%1d:%04X TDF File '%s': cannot obtain buffer for file: '%s"
#define HHCTA242E "%1d:%04X TDF File '%s': error reading file: '%s'"
#define HHCTA243E "%1d:%04X TDF File '%s': not a valid TDF file"
#define HHCTA244E "%1d:%04X TDF File '%s': cannot obtain buffer for TDF array: '%s'"
#define HHCTA245E "%1d:%04X TDF File '%s[%d]': filename or format missing"
#define HHCTA246E "%1d:%04X TDF File '%s[%d]': filename '%s' too long"
#define HHCTA247E "%1d:%04X TDF File '%s[%d]': RECSIZE keyword missing"
#define HHCTA248E "%1d:%04X TDF File '%s[%d]': invalid record size '%s'"
#define HHCTA249E "%1d:%04X TDF File '%s[%d]': invalid record format '%s'"

/* bldcfg.c cmdtab.c codepage.c config.c */
#define HHCMD001S "File '%s[%d]': error reading line: '%s'"
#define HHCMD002S "File '%s[%d]': line is too long"
#define HHCMD003S "File '%s': open error: '%s'"
#define HHCMD004S "File '%s': no device statements in file"
#define HHCMD008E "File '%s[%d]': syntax error: '%s'"
#define HHCMD009E "File '%s[%d]': incorrect number of operands"
#define HHCMD012S "File '%s[%d]': '%s' is not a valid CPU '%s'"
#define HHCMD013S "File '%s[%d]': invalid main storage size '%s'"
#define HHCMD014S "File '%s[%d]': invalid expanded storage size '%s'"
#define HHCMD016S "File '%s[%d]': invalid '%s' thread priority '%s'"
#define HHCMD017W "Hercules is not running as root, cannot raise '%s' thread priority"
#define HHCMD018S "File '%s[%d]': invalid number of CPUs '%s'"
#define HHCMD019S "File '%s[%d]': invalid number of VFs '%s'"
#define HHCMD020W "Vector Facility support not configured"
#define HHCMD022S "File '%s[%d]': invalid system epoch '%s'; valid range is 1801-2099"
#define HHCMD023S "File '%s[%d]': invalid timezone offset '%s'"
#define HHCMD029S "File '%s[%d]': invalid SHRDPORT port number '%s'"
#define HHCMD031S "Cannot obtain (%d)MB main storage: '%s'"
#define HHCMD032S "Cannot obtain storage key array: '%s'"
#define HHCMD033S "Cannot obtain (%d)MB expanded storage: '%s'"
#define HHCMD034W "Expanded storage support not installed"
#define HHCMD035S "File '%s[%d]': missing device number or device type"
#define HHCMD036S "File '%s[%d]': '%s' is not a valid device number(s) specification"
#define HHCMD040E "Cannot create processor '%s%02X' thread: '%s'"
#define HHCMD041E "%1d:%04X: device already exists"
#define HHCMD042E "%1d:%04X: devtype '%s' not recognized"
#define HHCMD043E "%1d:%04X: cannot obtain device block, function malloc() failed: '%s'"
#define HHCMD044E "%1d:%04X: device initialization failed"
#define HHCMD045E "%1d:%04X: cannot obtain buffer for device: '%s'"
#define HHCMD046E "%1d:%04X: %s does not exist"
#define HHCMD047I "%1d:%04X: %s detached"
#define HHCMD048E "%1d:%04X: device does not exist"
#define HHCMD049E "%1d:%04X: device already exists"
#define HHCMD051S "File '%s[%d]': invalid serial number: '%s'"
#define HHCMD052W "File '%s[%d]': invalid ECPSVM level value: '%s', 20 Assumed"
#define HHCMD053W "File '%s[%d]': invalid ECPSVM keyword: '%s', NO Assumed"
#define HHCMD054E "Incorrect device count near character(%c)"
#define HHCMD055E "Incorrect device address specification near character(%c)"
#define HHCMD056E "Incorrect device address range(%04X < %04X)"
#define HHCMD057E "%1d:%04X is on wrong channel (1st device defined on channel(%02X))"
#define HHCMD058E "Some or all devices in %04X-%04X duplicate devices already defined"
#define HHCMD059E "Incorrect second device number in device range near character(%c)"
#define HHCMD061W "File '%s[%d]': '%s' statement deprecated. Use '%s' instead"
#define HHCMD062W "File '%s[%d]': missing ECPSVM level value, 20 Assumed"
#define HHCMD063W "File '%s[%d]': specifying ECPSVM level directly is deprecated. Use the 'LEVEL' keyword instead"
#define HHCMD064W "Hercules set priority '%d' failed: '%s'"
#define HHCMD065I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCMD070S "File '%s[%d]': invalid year offset: '%s'"
#define HHCMD072W "SYSEPOCH '%04d' is deprecated, please specify \"SYSEPOCH 1900 '%s%d'\""
#define HHCMD073W "SYSEPOCH '%04d' is deprecated, please specify \"SYSEPOCH 1960 '%s%d'\""
#define HHCMD074S "File '%s[%d]': invalid engine syntax '%s'"
#define HHCMD075S "File '%s[%d]': invalid engine type '%s'"
#define HHCMD077I "Engine '%02d' set to type '%1d' '%s'"
#define HHCMD081I "File '%s': will ignore include errors"
#define HHCMD082S "File '%s[%d]': maximum nesting level '%d' reached"
#define HHCMD083I "File '%s': including file '%s' at '%d'"
#define HHCMD084W "File '%s': open error ignored file '%s': '%s'"
#define HHCMD085S "File '%s': open error file '%s': '%s'"
#define HHCMD086S "File '%s': NUMCPU '%d' must not exceed MAXCPU '%d'"
#define HHCMD090I "Default Allowed AUTOMOUNT directory = '%s'"
#define HHCMD139E "Unknown Hercules command: '%s', enter 'HELP' for a list of valid commands"
#define HHCMD140I "Valid panel commands are\n  %-9.9s    %s \n  %-9.9s    %s "
#define HHCMD142I "No HELP available. Unknown Hercules command: '%s'"
#define HHCMD151E "Codepage conversion table '%s' is not defined"
#define HHCMD152I "Using '%s' codepage conversion table '%s'"
#define HHCMD174E "Unspecified error occured while parsing Logical Channel Subsystem Identification"
#define HHCMD175E "No more than 1 Logical Channel Subsystem Identification may be specified"
#define HHCMD176E "Non-numeric Logical Channel Subsystem Identification '%s'"
#define HHCMD177E "Logical Channel Subsystem Identification '%d' exceeds maximum of '%d'"
#define HHCMD900S "Out of memory"




/* cckddasd.c */
#define HHCCD001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD002I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD020E "Invalid value %d for %s="
#define HHCCD021E "Invalid cckd keyword: %s"
#define HHCCD029E "Internal cckd trace table calloc() error, size(%d) %s"
#define HHCCD030I "Command parameters for cckd:\n" \
             "\thelp\t\tDisplay help message\n" \
             "\tstats\t\tDisplay cckd statistics\n" \
             "\topts\t\tDisplay cckd options\n" \
             "\tcomp=<n>\tOverride compression\t\t\t(-1 .. 2)\n" \
             "\tcompparm=<n>\tOverride compression parm\t\t(-1 .. 9)\n" \
             "\tra=<n>\t\tSet number readahead threads\t\t(1 .. 9)\n" \
             "\traq=<n>\t\tSet readahead queue size\t\t(0 .. 16)\n" \
             "\trat=<n>\t\tSet number tracks to read ahead\t\t(0 .. 16)\n" \
             "\twr=<n>\t\tSet number writer threads\t\t(1 .. 9)\n" \
             "\tgcint=<n>\tSet garbage collector interval (sec)\t(1 .. 60)\n" \
             "\tgcparm=<n>\tSet garbage collector parameter\t\t(-8 .. 8)\n" \
             "\tgcstart\t\tStart garbage collector\n" \
             "\tnostress=<n>\t1=Disable stress writes\n" \
             "\tfreepend=<n>\tSet free pending cycles\t\t\t(-1 .. 4)\n" \
             "\tfsync=<n>\t1=Enable fsync\n" \
             "\tlinuxnull=<n>\t1=Check for null linux tracks\n" \
             "\ttrace=<n>\tSet trace table size\t\t\t(0 .. 200000)"
#define HHCCD031I "cckd opts: comp=%d,compparm=%d,ra=%d,raq=%d,rat=%d," \
                  "wr=%d,gcint=%d,gcparm=%d,nostress=%d," \
                  "freepend=%d,fsync=%d,linuxnull=%d,trace=%d"
#define HHCCD040I "cckd stats:\n" \
              "\t  reads....%10" I64_FMT "d Kbytes...%10" I64_FMT "d writes...%10" I64_FMT "d Kbytes...%10" I64_FMT "d\n" \
              "\t  readaheads%9" I64_FMT "d misses...%10" I64_FMT "d syncios..%10" I64_FMT "d misses...%10" I64_FMT "d\n" \
              "\t  switches.%10" I64_FMT "d l2 reads.%10" I64_FMT "d strs wrt.%10" I64_FMT "d\n" \
              "\t  cachehits%10" I64_FMT "d misses...%10" I64_FMT "d l2 hits..%10" I64_FMT "d misses...%10" I64_FMT "d\n" \
              "\t  waits               i/o......%10" I64_FMT "d cache....%10" I64_FMT "d\n" \
              "\t  garbage collector   moves....%10" I64_FMT "d Kbytes...%10" I64_FMT "d"
#define HHCCD092I "%d devices processed"
#define HHCCD101E "%1d:%04X Error initializing shadow files"
#define HHCCD102E "%1d:%04X File[%d] get space error, size exceeds %lldM"
#define HHCCD110E "%1d:%04X File[%d] devhdr id error"
#define HHCCD121E "%1d:%04X File[%d] trklen err for %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD122E "%1d:%04X File[%d] invalid byte 0 trk(%d) buf(%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD123E "%1d:%04X File[%d] invalid byte 0 blkgrp(%d) buf(%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD124E "%1d:%04X File[%d] invalid %s hdr %s %d: %s compression unsupported"
#define HHCCD125E "%1d:%04X File[%d] invalid %s hdr %s %d buf(%p:%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD130E "%1d:%04X File[%d] %s open error: %s"
#define HHCCD131E "%1d:%04X File[%d] close error: %s"
#define HHCCD132E "%1d:%04X File[%d] lseek error, offset 0x%" I64_FMT "x: %s"
#define HHCCD133E "%1d:%04X File[%d] read error, offset 0x%" I64_FMT "x: %s"
#define HHCCD134E "%1d:%04X File[%d] read incomplete, offset 0x%" I64_FMT "x: read %d expected %d"
#define HHCCD135E "%1d:%04X File[%d] lseek error, offset 0x%" I64_FMT "x: %s"
#define HHCCD136E "%1d:%04X File[%d] write error, offset 0x%" I64_FMT "x: %s"
#define HHCCD137E "%1d:%04X File[%d] write incomplete, offset 0x%" I64_FMT "x: wrote %d expected %d"
#define HHCCD138E "%1d:%04X File[%d] ftruncate error, offset 0x%" I64_FMT "x: %s"
#define HHCCD139E "%1d:%04X Function malloc() error, size(%d) %s"
#define HHCCD140E "%1d:%04X Function calloc() error, size(%d) %s"
#define HHCCD142E "%1d:%04X File[%d] shadow file name(%s) collides with %1d:%04X file[%d] name(%s)"
#define HHCCD151E "%1d:%04X File[%d] error re-opening %s readonly: %s"
#define HHCCD160E "%1d:%04X Is not a cckd device"
#define HHCCD161E "%1d:%04X File[%d] no shadow file name"
#define HHCCD162E "%1d:%04X File[%d] max shadow files exceeded"
#define HHCCD163E "%1d:%04X File[%d] error adding shadow file"
#define HHCCD164I "%1d:%04X File[%d] %s added"
#define HHCCD165W "%1d:%04X Error adding shadow file, sf command busy on device"
#define HHCCD170E "%1d:%04X Is not a cckd device"
#define HHCCD171E "%1d:%04X File[%d] cannot remove base file"
#define HHCCD172E "%1d:%04X File[%d] not merged, file[%d] cannot be opened read-write%s"
#define HHCCD173E "%1d:%04X File[%d] not merged, file[%d] check failed"
#define HHCCD174E "%1d:%04X File[%d] not merged, file[%d] not hardened"
#define HHCCD175W "%1d:%04X File[%d] merge failed, sf command busy on device"
#define HHCCD179I "%1d:%04X Merging..."
#define HHCCD180E "%1d:%04X File[%d] not merged, error during merge"
#define HHCCD181I "%1d:%04X Shadow file [%d] successfully %s"
#define HHCCD182E "%1d:%04X File[%d] not merged, error processing trk(%d)"
#define HHCCD190E "%1d:%04X File[%d] offset 0x%" I64_FMT "x unknown space(%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD193E "%1d:%04X File[%d] uncompress error trk(%d) %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD194E "%1d:%04X File[%d] %s compression not supported"
#define HHCCD200I "%1d:%04X Compressing..."
#define HHCCD201I "%1d:%04X Checking level(%d)..."
#define HHCCD202W "%1d:%04X File[%d] check failed, sf command busy on device"
#define HHCCD205W "%1d:%04X Is not a cckd device"
#define HHCCD206W "%1d:%04X File[%d] compress failed, sf command busy on device"
#define HHCCD207I "%1d:%04X Adding..."
#define HHCCD208I "%1d:%04X Display cckd stats"
#define HHCCD209W "%1d:%04X Is not a cckd device"
#define HHCCD210I "%1d:%04X           size free  nbr st   reads  writes l2reads    hits switches"
#define HHCCD211I "%1d:%04X                                                  readaheads   misses"
#define HHCCD212I "%1d:%04X --------------------------------------------------------------------"
#define HHCCD213I "%1d:%04X [*] %10" I64_FMT "d %3" I64_FMT "d%% %4d    %7d %7d %7d %7d  %7d"
#define HHCCD214I "%1d:%04X                                                     %7d  %7d"
#define HHCCD215I "%1d:%04X %s"
#define HHCCD216I "%1d:%04X [0] %10" I64_FMT "d %3" I64_FMT "d%% %4d %s %7d %7d %7d"
#define HHCCD217I "%1d:%04X %s"
#define HHCCD218I "%1d:%04X [%d] %10" I64_FMT "d %3" I64_FMT "d%% %4d %s %7d %7d %7d"
#define HHCCD900I "Internal cckd trace"
#define HHCCD901I "%s"
#define HHCCD902I "%1d:%04X %s"
#define HHCCD908I "Internal cckd trace table is empty"
#define HHCCD909I "Internal cckd trace is off"

/* channel.c */
#define HHCCP048I "%1d:%04X CCW(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X%s)"
#define HHCCP049I "%1d:%04X Stat(%2.2X%2.2X) Count(%2.2X%2.2X) CCW(%2.2X%2.2X%2.2X)"
#define HHCCP050I "%1d:%04X SCSW(%2.2X%2.2X%2.2X%2.2X) Stat(%2.2X%2.2X) Count(%2.2X%2.2X) CCW(%2.2X%2.2X%2.2X%2.2X)"
#define HHCCP051I "%1d:%04X Test I/O"
#define HHCCP052I "%1d:%04X TIO modification executed CC=1"
#define HHCCP053I "%1d:%04X Halt I/O"
#define HHCCP054I "%1d:%04X HIO modification executed CC=1"
#define HHCCP055I "%1d:%04X Clear subchannel"
#define HHCCP056I "%1d:%04X Halt subchannel"
#define HHCCP057I "%1d:%04X Halt subchannel: cc=%d"
#define HHCCP060I "%1d:%04X Resume subchannel: cc=%d"
#define HHCCP078I "%1d:%04X MIDAW(%2.2X %4.4"I16_FMT"X %16.16"I64_FMT"X): %s"
#define HHCCP063I "%1d:%04X IDAW(%8.8"I32_FMT"X) Len(%3.3"I16_FMT"X): %s"
#define HHCCP064I "%1d:%04X IDAW(%16.16"I64_FMT"X) Len(%4.4"I16_FMT"X): %s"
#define HHCCP065I "%1d:%04X attention signaled"
#define HHCCP066I "%1d:%04X attention"
#define HHCCP067E "%1d:%04X create_thread error: %s"
#define HHCCP069I "%1d:%04X initial status interrupt"
#define HHCCP070I "%1d:%04X attention completed"
#define HHCCP071I "%1d:%04X clear completed"
#define HHCCP072I "%1d:%04X halt completed"
#define HHCCP073I "%1d:%04X suspended"
#define HHCCP074I "%1d:%04X resumed"
#define HHCCP075I "%1d:%04X Stat(%2.2X%2.2X) Count(%4.4X) %s"
#define HHCCP076I "%1d:%04X Sense(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X)"
#define HHCCP077I "%1d:%04X Sense(%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s)"
#define HHCCP100I "%1d:%04X asynchronous I/O ccw addr %8.8x"
#define HHCCP101I "%1d:%04X synchronous  I/O ccw addr %8.8x"

/* ckddasd.c */
#define HHCDA001E "%1d:%04X File name missing or invalid"
#define HHCDA002E "%1d:%04X File '%s' not found or invalid filename length"
#define HHCDA003E "%1d:%04X Parameter(%s) number(%d) is invalid"
#define HHCDA004I "%1d:%04X File '%s': opening as R/O%s"
#define HHCDA005E "%1d:%04X File '%s': open error: '[%02d] %s'"
#define HHCDA006E "%1d:%04X File '%s': not in a single file for shadowing"
#define HHCDA007E "%1d:%04X File '%s': fstat error: '[%02d] %s'"
#define HHCDA008E "%1d:%04X File '%s': read error: '[%02d] %s'"
#define HHCDA009E "%1d:%04X File '%s': CKD header incomplete"
#define HHCDA010E "%1d:%04X File '%s': CKD header invalid"
#define HHCDA011E "%1d:%04X File '%s': Only 1 CCKD file allowed"
#define HHCDA013E "%1d:%04X File '%s': CCKD header incomplete"
#define HHCDA014E "%1d:%04X File '%s': CKD file out of sequence"
#define HHCDA015I "%1d:%04X File '%s': seq(%d) cyls(%d-%d)"
#define HHCDA016E "%1d:%04X File '%s': heads(%d) trklen(%d), expected heads(%d) trklen(%d)"
#define HHCDA017E "%1d:%04X File '%s': CKD header inconsistent with file size"
#define HHCDA018E "%1d:%04X File '%s': CKD header high cylinder incorrect"
#define HHCDA019E "%1d:%04X File '%s': exceeds maximum CKD files(%d)"
#define HHCDA020I "%1d:%04X File '%s': cyls(%d) heads(%d) tracks(%d) trklen(%d)"
#define HHCDA021E "%1d:%04X Device type(%4.4X) not found in dasd table"
#define HHCDA022E "%1d:%04X Control unit(%s) not found in dasd table"
#define HHCDA023I "%1d:%04X Cache hits(%d), misses(%d), waits(%d)"
#define HHCDA024I "%1d:%04X Read trk(%d) cur trk(%d)"
#define HHCDA025I "%1d:%04X Read track: updating track(%d)"
#define HHCDA026E "%1d:%04X Error writing trk(%d): lseek error '[%02d] %s'"
#define HHCDA027E "%1d:%04X Error writing trk(%d): write error '[%02d] %s'"
#define HHCDA028I "%1d:%04X Read trk(%d) cache hit, using cache[%d]"
#define HHCDA029I "%1d:%04X Read trk(%d) no available cache entry, waiting"
#define HHCDA030I "%1d:%04X Read trk(%d) cache miss, using cache[%d]"
#define HHCDA031I "%1d:%04X Read trk(%d) reading file(%d) offset(%" I64_FMT "d) len(%d)"
#define HHCDA032E "%1d:%04X Error reading trk(%d): lseek error '[%02d] %s'"
#define HHCDA033E "%1d:%04X Error reading trk(%d): read error '%s'"
#define HHCDA034I "%1d:%04X Read trk(%d) trkhdr(%02X %02X%02X %02X%02X)"
#define HHCDA035E "%1d:%04X Invalid track header for cyl(%d) head(%d) %02X%02X%02X%02X%%02X"
#define HHCDA036E "%1d:%04X Error: wrong recordheader: cc hh r=%d %d %d, should be:cc hh r=%d %d %d"
#define HHCDA038I "%1d:%04X Seeking to cyl(%d) head(%d)"
#define HHCDA039E "%1d:%04X Error: MT advance: locate record(%d) file mask(%02X)"
#define HHCDA040I "%1d:%04X MT advance to cyl(%d) head(%d)"
#define HHCDA041I "%1d:%04X Read count orientation(%s)"
#define HHCDA042E "%1d:%04X Error attempting to read past end of track '%d %d'"
#define HHCDA043I "%1d:%04X Cyl(%d) head(%d) record(%d) kl(%d) dl(%d) of(%d)"
#define HHCDA044I "%1d:%04X Read key %d bytes"
#define HHCDA045I "%1d:%04X Read data %d bytes"
#define HHCDA046E "%1d:%04X Error attempting to read past end of track"
#define HHCDA047I "%1d:%04X Writing cyl(%d) head(%d) record(%d) kl(%d) dl(%d)"
#define HHCDA048I "%1d:%04X Setting track overflow flag for cyl(%d) head(%d) record(%d)"
#define HHCDA049E "%1d:%04X Error write KD orientation"
#define HHCDA050I "%1d:%04X Updating cyl(%d) head(%d) record(%d) kl(%d) dl(%d)"
#define HHCDA051E "%1d:%04X Error write data orientation"
#define HHCDA052I "%1d:%04X Updating cyl(%d) head(%d) record(%d) dl(%d)"
#define HHCDA053E "%1d:%04X Error, DC (data chaining) not supported for CCW '%02X'"
#define HHCDA054I "%1d:%04X Set file mask '%02X'"
#define HHCDA055I "%1d:%04X Search key '%s'"

/* cmdtab.c */
#define HHCMD853I "CMDLEVEL invalid option: %s"
#define HHCMD854I "cmdlevel[%2.2X] is %s"

/* fbadasd.c */
#define HHCDA056E "%1d:%04X File name missing or invalid"
#define HHCDA057E "%1d:%04X File not found or invalid"
#define HHCDA058E "%1d:%04X File(%s) open error %s"
#define HHCDA059E "%1d:%04X Read error in file(%s) %s"
#define HHCDA060E "%1d:%04X Unexpected end of file(%s)"
#define HHCDA063E "%1d:%04X Parameter(%d) is invalid %s"
#define HHCDA064E "%1d:%04X File(%s) fstat error %s"
#define HHCDA065E "%1d:%04X Invalid device origin block number(%s)"
#define HHCDA066E "%1d:%04X Invalid device block count(%s)"
#define HHCDA067I "%1d:%04X File(%s) origin(%lld) blks(%d)"
#define HHCDA068E "%1d:%04X device type(%4.4X) not found in dasd table"
#define HHCDA069E "%1d:%04X Error writing blkgrp(%d) lseek error(%s)"
#define HHCDA070E "%1d:%04X Error writing blkgrp(%d) write error(%s)"
#define HHCDA071I "%1d:%04X Read blkgrp(%d) cache hit, using cache[%d]"
#define HHCDA072I "%1d:%04X Read blkgrp(%d) no available cache entry, waiting"
#define HHCDA073I "%1d:%04X Read blkgrp(%d) cache miss, using cache[%d]"
#define HHCDA074I "%1d:%04X Read blkgrp(%d) offset(%" I64_FMT "d) len(%d)"
#define HHCDA075E "%1d:%04X Error reading blkgrp(%d) lseek error(%s)"
#define HHCDA076E "%1d:%04X Error reading blkgrp(%d) read error(%s)"
#define HHCDA077I "%1d:%04X Positioning to %8.8" I64_FMT "X (%" I64_FMT "u)"
#define HHCDA078E "%1d:%04X Define extent data too short: %d bytes"
#define HHCDA079E "%1d:%04X Second define extent in chain"
#define HHCDA080E "%1d:%04X Invalid file mask(%2.2X)"
#define HHCDA081E "%1d:%04X Invalid extent: first block(%d) last block(%d) numblks(%d) device size(%d)"
#define HHCDA082E "%1d:%04X File(%s) IOCTL BLKGETSIZE error %s"
#define HHCDA083I "%1d:%04X REAL FBA opened"                   
#define HHCDA901E "%1d:%04X FBA origin mismatch: %d, expected %d,"
#define HHCDA902E "%1d:%04X FBA numblk mismatch: %d, expected %d,"
#define HHCDA903E "%1d:%04X FBA blksiz mismatch: %d, expected %d,"

/* comm3705.c and commadpt.c */
#define HHCCA001I "Client(%s) connected to %4.4X device(%4.4X)"
#define HHCCA002I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCA003E "%1d:%04X Cannot obtain socket for incoming calls: %s"
#define HHCCA004W "%1d:%04X Waiting 5 seconds for port(%d) to become available"
#define HHCCA005I "%1d:%04X Listening on port(%d) for incoming TCP connections"
#define HHCCA006T "%1d:%04X Select failed: %s"
#define HHCCA007W "%1d:%04X Outgoing call failed during %s command: %s"
#define HHCCA008I "%1d:%04X Incoming Call"
#define HHCCA009I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCA010I "%1d:%04X Initialization not performed"
#define HHCCA011E "%1d:%04X Error parsing %s"
#define HHCCA012E "%1d:%04X Unrecognized parameter(%s)"
#define HHCCA013E "%1d:%04X Incorrect %s specification %s"
#define HHCCA014E "%1d:%04X Incorrect switched/dial specification(%s): defaulting to DIAL=OUT"
#define HHCCA015E "%1d:%04X Missing parameter: DIAL(%s) and %s not specified"
#define HHCCA016W "%1d:%04X Conflicting parameter: DIAL(%s) and %s=%s specified"
#define HHCCA017I "%1d:%04X RPORT parameter ignored"
#define HHCCA018E "%1d:%04X Bind failed: %s"
#define HHCCA019E "%1d:%04X BSC comm thread did not initialize"
#define HHCCA020E "%1d:%04X Memory allocation failure for main control block"
#define HHCCA021I "%1d:%04X Initialization failed due to previous errors"
#define HHCCA022E "Cannot create commadpt thread: %s"
#define HHCCA023I "%1d:%04X Connect out to %s:%d failed during initial status: %s"
#define HHCCA024E "%1d:%04X No buffers trying to send SNA request2"
#define HHCCA025E "%1d:%04X No buffers trying to send SNA request3"
#define HHCCA026E "%1d:%04X No buffers trying to send SNA request4"
#define HHCCA027E "%1d:%04X No buffers trying to send SNA request5"
#define HHCCA028E "%1d:%04X No buffers trying to send SNA request"
#define HHCCA029E "%1d:%04X No buffers trying to send SNA response"
//#define HHCCA300D in comm3705.c and commadpt.c

/* con1052c.c */
#define HHCON001A "%1d:%04X Enter input for console device"
#define HHCON008I "%1d:%04X %s %s"
#define HHCON009I "%1d:%04X RRRRINGGGG!\a"
#define HHCON010I "%1d:%04X %s"

/* console.c and comm3705.c */
#define HHCGI001I "Unable to determine IP address from (%s)"
#define HHCGI002I "Unable to determine port number from (%s)"
#define HHCGI003E "Invalid parameter(%s)"

#define HHCTE001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTE002W "Waiting for port(%u) to become free"
#define HHCTE003I "Waiting for console connection on port(%u)"
#define HHCTE004I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)" 
#define HHCTE006A "%1d:%04X Enter console input"
#define HHCTE005E "Cannot create console thread: (%s)"
#define HHCTE007I "%1d:%04X Devtype(%4.4X) client(%s) connection closed"
#define HHCTE008I "%1d:%04X Connection closed by client(%s)"
#define HHCTE009I "%1d:%04X Client(%s) devtype(%4.4X): connected"
#define HHCTE010E "CNSLPORT statement invalid: (%s)"
#define HHCTE011E "%1d:%04X Invalid IP address: (%s)"
#define HHCTE012E "%1d:%04X Invalid mask value: (%s)"
#define HHCTE013E "%1d:%04X Extraneous argument(s): (%s)..."
#define HHCTE014I "%1d:%04X Client(%s) devtype(%4.4X): connection reset"
#define HHCTE017E "%1d:%04X Duplicate SYSG console definition"
#define HHCTE090E "%1d:%04X Malloc() failed for resume buf: (%s)"

/* cpu.c */
#define HHCCP001W "Processor(%s%02X) thread set priority(%d) failed: (%s)"
#define HHCCP002I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(processor %s%02X)"
#define HHCCP003I "Processor(%s%02X) architecture mode(%s)"
#define HHCCP004I "Processor(%s%02X) Vector Facility online"
#define HHCCP006S "Cannot create timer thread: (%s)"
#define HHCCP007I "Processor(%s%02X) architecture mode(%s) set"
#define HHCCP008I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(processor %s%02X)"
#define HHCCP010I "Processor(%s%02X) store status completed"
#define HHCCP011I "Processor(%s%02X) disabled wait state(%s)"
#define HHCCP014I "%s%s%s%02X: (%s) code(%4.4X) ilc(%d%s)"
#define HHCCP015I "Processor(%s%02X) PER event: code(%4.4X) perc(%2.2X) addr(" F_VADR ")"
#define HHCCP016I "Processor(%s%02X) Program interrupt loop: PSW(%s)"
#define HHCCP022I "Machine Check code (%16.16" I64_FMT "u)"
#define HHCCP043I "Wait state PSW loaded: (%s)"
#define HHCCP044I "I/O interrupt code(%4.4X) CSW(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X)"
#define HHCCP045I "I/O interrupt code(%8.8X) parm(%8.8X)"
#define HHCCP046I "I/O interrupt code(%8.8X0 parm(%8.8X), id(%8.8X)"
#define HHCCP080E "Processor(%s%02X) malloc failed for archjmp regs: (%s)"

/* crypto/dyncrypt.c */
#define HHCRY001I "Crypto module loaded (c) Copyright Bernard van der Helm, 2003-2010"
#define HHCRY002I "Activated facility: '%s'"

/* ctc_ctci.c */
#define HHCCT037E "%1d:%04X Unable to allocate CTCBLK"
#define HHCCT040I "%1d:%04X Halt or Clear Recognized"
#define HHCCT041I "%1d:%04X CTC Received Frame (%d bytes)"
#define HHCCT042E "%1d:%04X Write CCW count(%u) is invalid"
#define HHCCT043I "%1d:%04X Interface command: %s %8.8X"
#define HHCCT044E "%1d:%04X Write buffer contains incomplete segment header at offset(%4.4X)"
#define HHCCT045E "%1d:%04X Write buffer contains invalid segment length(%u) at offset(%4.4X)"
#define HHCCT046I "%1d:%04X Sending packet to device(%s)"
#define HHCCT047E "%1d:%04X Error writing to device(%s): %s"
#define HHCCT048E "%1d:%04X Error reading from device(%s): %s"
#define HHCCT049I "%1d:%04X Received packet from device(%s) (%d bytes)"
#define HHCCT056E "%1d:%04X Incorrect number of parameters"
#define HHCCT050E "%1d:%04X Invalid adapter address(%s)"
#define HHCCT051E "%1d:%04X Invalid device name(%s)"
#define HHCCT052E "%1d:%04X Invalid kernel buffer size(%s)"
#define HHCCT053E "%1d:%04X Invalid DLL I/O buffer size(%s)"
#define HHCCT054E "%1d:%04X Invalid MTU size(%s)"
#define HHCCT055E "%1d:%04X Invalid netmask(%s)"
#define HHCCT056E "%1d:%04X Incorrect number of parameters"
#define HHCCT057E "%1d:%04X Invalid MAC address(%s)"
#define HHCCT058E "%1d:%04X Invalid IP address(%s)"
#define HHCCT061E "%1d:%04X invalid device name(%s)"
#define HHCCT062E "%1d:%04X Invalid MTU size(%s)"
#define HHCCT072W "%1d:%04X Packet too big; dropped"
#define HHCCT073I "%1d:%04X TUN device(%s) opened"
#define HHCCT074W "TT32SDEVBUFF failed for device(%s): %s"
#define HHCCT075W "TT32SIOBUFF failed for device(%s): %s"

/* ctc_lcs.c */
#define HHCLC001E "Device(%4.4X) Unable to allocate LCSBLK"
#define HHCLC002I "Device(%4.4X) Halt or Clear Recognized"
#define HHCLC003I "Device(%4.4X) LCS Read"
#define HHCLC004I "Device(%4.4X) Sending packet to file(%s)"
#define HHCLC005E "Device(%4.4X) Error writing to file(%s) %s"
#define HHCLC006I "Device(%4.4X) Triggering Event"
#define HHCLC007E "Error in call to socket: %s"
#define HHCLC008E "ioctl error on device(%s) %s"
#define HHCLC009I "Port(%2.2X) Read Buffer:"
#define HHCLC010I "Port(%2.2X) IPV4 frame for %8.8X"
#define HHCLC011I "Port(%2.2X) ARP frame for %8.8X"
#define HHCLC012I "Port(%2.2X) SNA frame"
#define HHCLC013I "Port(%2.2X) No match found - selecting primary %4.4X"
#define HHCLC014I "Port(%2.2X) No match found - selecting secondary %4.4X"
#define HHCLC015I "Port(%2.2X) No match found - Discarding frame"
#define HHCLC016I "Port(%2.2X) Enqueing frame to device %4.4X (%8.8X)"
#define HHCLC017E "Device(%4.4X) invalid device name(%s)"
#define HHCLC018E "Device(%4.4X) invalid MAC address(%s)"
#define HHCLC019E "Device(%4.4X) too many arguments in statement"
#define HHCLC020E "Device(%4.4X) invalid IP address(%s)"
#define HHCLC021E "Invalid HWADD statement in %s: %s"
#define HHCLC022E "Invalid MAC in HWADD statement in %s: %s (%s)"
#define HHCLC023E "Invalid ROUTE statement in %s: %s"
#define HHCLC024E "Invalid net address in ROUTE %s: %s (%s)"
#define HHCLC025E "Invalid net mask in ROUTE %s: %s (%s)"
#define HHCLC026E "Error in %s: Missing device number or mode"
#define HHCLC027E "Error in %s: %s: Invalid device number"
#define HHCLC028E "Error in %s: %s: Missing PORT number"
#define HHCLC029E "Error in %s: %s: Invalid PORT number"
#define HHCLC031E "Error in %s: %s: Invalid entry starting at %s"
#define HHCLC032E "Error in %s: %s: Invalid IP address (%s)"
#define HHCLC033E "Error in %s: %s: Missing PORT number"
#define HHCLC034E "Error in %s: %s: Invalid PORT number"
#define HHCLC035E "Error in %s: %s: SNA does not accept any arguments"
#define HHCLC036E "Error in %s: %s: Invalid MODE"
#define HHCLC037E "Error reading file(%s) line(%d): %s"
#define HHCLC038E "File(%s) line(%d) is too long"
#define HHCLC039E "Cannot open file(%s): %s"
#define HHCLC040E "Device(%4.4X) LCSDEV(%4.4X) not in configuration"
#define HHCLC041W "Port(%2.2X) Frame too big; discarded"
#define HHCLC042E "Port(%2.2X) Read error: %s"
#define HHCLC043I "Device(%4.4X) Startup"
#define HHCLC044I "Device(%4.4X) Shutdown"
#define HHCLC045I "Device(%4.4X) Start LAN"
#define HHCLC046I "Device(%4.4X) Stop LAN"
#define HHCLC047I "Device(%4.4X) Query IP Assists"
#define HHCLC048I "Device9%4.4X) Statistics"
#define HHCLC049W "Device(%4.4X) LCS_Startup: Requested frame buffer size of 0x%4.4X larger than compiled size of 0x%4.4X; requested size ignored"
#define HHCLC050E "Device(%4.4X) LCS_Write: Unsupported frame type(0x%2.2X)"
#define HHCLC051I "Device(%4.4X) Cmd Packet"
#define HHCLC052E "Device(%4.4X) Invalid kernel buffer size(%s)"
#define HHCLC053E "Device(%4.4X) Invalid DLL I/O buffer size(%s)"
#define HHCLC054W "Device(%4.4X) LCS_Startup: Requested frame buffer size of 0x%4.4X smaller than compiled minimum size of 0x%4.4X; requested size ignored"
#define HHCLC055I "%s using MAC %2.2X:%2.2X:%2.2X:%2.2X:%2.2X:%2.2X"
#define HHCLC056W "%s NOT using MAC %2.2X:%2.2X:%2.2X:%2.2X:%2.2X:%2.2X"
#define HHCLC073I "Device(%4.4X) TAP device(%s) opened"
#define HHCLC074W "TT32SDEVBUFF failed for device(%s) %s"
#define HHCLC075W "TT32SIOBUFF failed for device(%s) %s"
#define HHCLC076I "Port(%2.2X) RARP frame for %2.2X:%2.2X:%2.2X:%2.2X:%2.2X:%2.2X"

/* ctcadpt.c */
#define HHCCT001E "Device(%4.4X) Incorrect number of parameters"
#define HHCCT002E "Device(%4.4X) Incorrect number of parameters"
#define HHCCT003E "Device(%4.4X) Invalid port number(%s)"
#define HHCCT004E "Device(%4.4X) Invalid IP address(%s)"
#define HHCCT005E "Device(%4.4X) Invalid port number(%s)"
#define HHCCT006E "Device(%4.4X) Invalid MTU size(%s)"
#define HHCCT007E "Device(%4.4X) Error creating socket(%s)"
#define HHCCT008E "Device(%4.4X) Error binding socket(%s)"
#define HHCCT009I "Device(%4.4X) Connect to %s:%s failed, starting server"
#define HHCCT010E "Device(%4.4X) Error creating socket: %s"
#define HHCCT011E "Device(%4.4X) Error binding socket(%s)"
#define HHCCT012E "Device(%4.4X) Error on call to listen: %s"
#define HHCCT013I "Device(%4.4X) Connected to %s:%s"
#define HHCCT014E "Device(%4.4X) Write CCW count %u is invalid"
#define HHCCT015I "Device(%4.4X) Interface command: %s %8.8X"
#define HHCCT016E "Device(%4.4X) Write buffer contains incomplete segment header at offset %4.4X"
#define HHCCT017E "Device(%4.4X) Write buffer contains invalid segment length %u at offset %4.4X"
#define HHCCT018I "Device(%4.4X) Sending packet to file(%s)"
#define HHCCT019E "Device(%4.4X) Error writing to file(%s): %s"
#define HHCCT020E "Device(%4.4X) Error reading from file(%s): %s"
#define HHCCT021E "Device(%4.4X) Error reading from file(%s): %s"
#define HHCCT022I "Device(%4.4X) Received packet from %s (%d bytes)"
#define HHCCT023E "Device(%4.4X) Incorrect client or config error: Config(%s) connecting client(%s)"
#define HHCCT024E "Device(%4.4X) Not enough arguments to start vmnet"
#define HHCCT025E "Device(%4.4X) Failed: socketpair: %s"
#define HHCCT026E "Device(%4.4X) Failed: fork: %s"
#define HHCCT027E "Device(%4.4X) Not enough parameters"
#define HHCCT028E "%1d:%04X Bad device number(%s)"
#define HHCCT029E "Device(%4.4X) bad block length: %d < %d"
#define HHCCT030E "Device(%4.4X) bad packet length: %d < %d"
#define HHCCT032E "Device(%4.4X) Error: EOF on read, CTC network down"
#define HHCCT033E "Device(%4.4X) Error: read: %s"
#define HHCCT034E "Unrecognized/unsupported CTC emulation type(%s)"

/* diagnose.c */
#define HHCDN001I "Diagnose 0x308 called: System is re-ipled"
#define HHCDN002I "Checking cpu(%d)"
#define HHCDN003I "Waiting 1 second for cpu's to stop"
#define HHCDN004E "Error starting thread in diagnose 0x308: %s"

/* dynguic. */
#define HHCDG001I "Dyngui.dll initiated"
#define HHCDG002I "Dyngui.dll terminated"
#define HHCDG003S "Select failed on input stream: %s"
#define HHCDG004S "Read failed on input stream: %s"
#define HHCDG005E "Device(%4.4X) query buffer overflow"

/* ecpsvm.c */
#define HHCEV001I "| %-9s | %8d | %8d |  %3d%% |"
#define HHCEV002I "| %-9s | %-8s | %-8s | %-5s |"
#define HHCEV003I "+-----------+----------+----------+-------+"
#define HHCEV004W "Abend condition detected in DISP2 instr"
#define HHCEV005I "%d Entr%s not shown (never invoked)"
#define HHCEV006I "%d call(s) was/where made to unsupported functions"
#define HHCEV008E "NO EVM subcommand. Type \"evm help\" for a list of valid subcommands"
#define HHCEV010I "%s : %s"
#define HHCEV011E "Unknown subcommand %s - valid subcommands are :"
#define HHCEV012I "%s : %s"
#define HHCEV013I "ECPS:VM Global Debug %s"
#define HHCEV014I "ECPS:VM %s feature %s %s%s"
#define HHCEV015I "ECPS:VM %s feature %s%s%s"
#define HHCEV016I "All ECPS:VM %s features %s%s"
#define HHCEV017I "But ECPS:VM is currently disabled"
#define HHCEV018W "WARNING ! Unpredictable results may occur"
#define HHCEV019I "The microcode support level is 20"
#define HHCEV024I "* : Unsupported, - : Disabled, %% - Debug"
#define HHCEV025I "Unknown ECPS:VM feature %s; Ignored"
#define HHCEV026I "Current reported ECPS:VM Level is %d"
#define HHCEV027I "Level reported to guest program is now %d"
#define HHCEV028W "WARNING ! current level (%d) is not supported"
#define HHCEV029I "ECPS:VM Command processor invoked"
#define HHCEV030E "Unknown EVM subcommand %s"
#define HHCEV031I "ECPS:VM Command processor complete"
//#define HHCEV300D in ecpsvm.c

/* external.c */
#define HHCCP023I "External interrupt: Interrupt key"
#define HHCCP024I "External interrupt: Clock comparator"
#define HHCCP025I "External interrupt: CPU timer=%16.16" I64_FMT "X"
#define HHCCP026I "External interrupt: Interval timer"
#define HHCCP027I "External interrupt: Service signal %8.8X"
#define HHCCP028I "External interrupt: Block I/O %s"
#define HHCCP031I "%1d:%04X Processing Block I/O interrupt: code(%4.4X) parm(%16.16X) status(%2.2X) subcode(%2.2X)"

/* hao.c */
#define HHCAO001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCAO002I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCAO003I "Firing command: (%s)"
#define HHCAO004I "The defined Automatic Operator rule(s) are:"
#define HHCAO005I "(%02d): (%s) -> (%s)"
#define HHCAO006I "(%d) rule(s) displayed"
#define HHCAO007E "Unknown hao command, valid commands are:\n" \
                  "          hao tgt <tgt> : define target rule (pattern) to react on\n" \
                  "          hao cmd <cmd> : define command for previously defined rule\n" \
                  "          hao list <n>  : list all rules/commands or only at index <n>\n" \
                  "          hao del <n>   : delete the rule at index <n>\n" \
                  "          hao clear     : delete all rules (stops automatic operator)"
#define HHCAO008E "No rule defined at index(%d)"
#define HHCAO009E "Invalid index, index must be between 0 and (%d)"
#define HHCAO010E "Target not added, table full"
#define HHCAO011E "Tgt command given, but cmd command expected"
#define HHCAO012E "Empty target specified"
#define HHCAO013E "Target not added, duplicate found in table"
#define HHCAO014E "%s"
#define HHCAO015E "%s"
#define HHCAO016I "Target placed at index(%d)"
#define HHCAO017E "Cmd command given, but tgt command expected"
#define HHCAO018E "Empty command specified"
#define HHCAO019E "Command not added; causes loop with target at index(%d)"
#define HHCAO020I "Command placed at index(%d)"
#define HHCAO021E "Target not added, causes loop with command at index(%d)"
#define HHCAO022I "All automatic operation rules cleared"
#define HHCAO023E "Hao del command given without a valid index"
#define HHCAO024E "Rule at index(%d) not deleted, already empty"
#define HHCAO025I "Rule at index(%d) succesfully deleted"
#define HHCA0026E "Command not added, may cause dead locks"

/* hchan.c */
#define HHCHC001E "Device(%4.4X) Incorrect Generic Channel method(%s)"
#define HHCHC002T "Device(%4.4X) Generic channel initialisation failed"
#define HHCHC003E "Device(%4.4X) Missing Generic Channel method"
#define HHCHC999W "Device(%4.4X) Generic channel is currently in development"

/* hdl.c */
#define HHCHD001E "Registration malloc failed for (%s)"
#define HHCHD005E "Module(%s) already loaded"
#define HHCHD006S "Cannot allocate memory for DLL descriptor: (%s)"
#define HHCHD007E "Unable to open DLL(%s): (%s)"
#define HHCHD008E "Device(%4.4X) bound to (%s)"
#define HHCHD009E "Module(%s) not found"
#define HHCHD010I "Dependency check failed for (%s), version(%s) expected(%s)"
#define HHCHD011I "Dependency check failed for (%s), size(%d) expected(%d)"
#define HHCHD013E "No dependency section in (%s): (%s)"
#define HHCHD014E "Dependency check failed for module(%s)"
#define HHCHD015E "Unloading of module(%s) not allowed"
#define HHCHD016E "DLL(%s) is duplicate of (%s)"
#define HHCHD017E "Unload of module(%s) rejected by final section"
#define HHCHD018I "Loadable module directory is (%s)"
#define HHCHD019E "Loadable module directory path name length '%d' exceeds maximum of '%d'" 
#define HHCHD900I "Begin shutdown sequence"
#define HHCHD901I "Calling (%s)"
#define HHCHD902I "(%s) complete"
#define HHCHD903I "(%s) skipped during Windows SHUTDOWN immediate"
#define HHCHD909I "Shutdown sequence complete"
#define HHCHD950I "Begin HDL termination sequence"
#define HHCHD951I "Calling module(%s) cleanup routine"
#define HHCHD952I "Module(%s) cleanup complete"
#define HHCHD959I "HDL Termination sequence complete"

/* hettape.c */
#define HHCTA401I "%1d:%04X Tape file(%s) Closed; HET format tape"
#define HHCTA402E "%1d:%04X Tape file(%s) Open error: HETERR(%s): (%s)"
#define HHCTA403E "%1d:%04X Tape file(%s) Error seeking to start of file: HETERR(%s): (%s)"
#define HHCTA405E "%1d:%04X Tape file(%s) End of file (end of tape) at block("I32_FMTX")"
#define HHCTA409E "%1d:%04X Tape file(%s) Error reading data block at block("I32_FMTX"): HETERR(%s): (%s)"
#define HHCTA416E "%1d:%04X Tape file(%s) Error writing data block at block("I32_FMTX"): HETERR(%s): (%s)"
#define HHCTA417E "%1d:%04X Tape file(%s) Error writing tape mark at block("I32_FMTX"): HETERR(%s): (%s)"
#define HHCTA418E "%1d:%04X Tape file(%s) Error forward spacing at block("I32_FMTX"): HETERR(%s): (%s)"
#define HHCTA419E "%1d:%04X Tape file(%s) Error forward spacing to next file at block("I32_FMTX"): HETERR(%s): (%s)"
#define HHCTA420E "%1d:%04X Tape file(%s) Sync error: (%s)"
#define HHCTA421E "%1d:%04X Tape file(%s) Error back spacing to previous file at block("I32_FMTX"): HETERR(%s): (%s)"
#define HHCTA430I "%1d:%04X Tape file(%s) Maximum tape capacity exceeded"
#define HHCTA431I "%1d:%04X Tape file(%s) Maximum tape capacity enforced"

/* hostinfo.c */
#define HHCIN015I "%s"

/* hsccmd.c */
#define HHCMD001W "Ignoring invalid SCRIPT file pause statement: %s"
#define HHCMD002I "EOF reached on SCRIPT file. Processing complete"
#define HHCMD003E "I/O error reading SCRIPT file: %s"
#define HHCMD004I "Message level %d"
#define HHCMD007E "Script file \"%s\" open failed: %s"
#define HHCMD008I "Script file processing started using file \"%s\""
#define HHCMD011I "Pausing SCRIPT file processing for %d seconds..."
#define HHCMD012I "Resuming SCRIPT file processing..."
#define HHCMD013I "SHCMDOPT %sabled%s"
#define HHCMD015S "Invalid program product OS license setting %s"
#define HHCMD016I "Panel refresh rate = %d millisecond(s)"
#define HHCMD017E "%1d:%04X is not a printer"
#define HHCMD018I "%1d:%04X Printer started"
#define HHCMD019E "%1d:%04X Printer not started: %s"
#define HHCMD021E "Device address is missing"
#define HHCMD025I "%1d:%04X Printer stopped"
#define HHCMD026W "Quiet command ignored: external GUI active"
#define HHCMD027I "Automatic refresh %s"
#define HHCMD028I "ASN and LX reuse is %s"
#define HHCMD029E "Invalid I/O delay value: %s"
#define HHCMD030I "I/O delay = %d"
#define HHCMD031E "Missing device number"
#define HHCMD032I "CTC debugging now %s for %s device %1d:%04X group"
#define HHCMD033I "CTC debugging now %s for all CTCI/LCS device groups"
#define HHCMD034E "%1d:%04X is not a CTCI or LCS"
#define HHCMD035E "store status rejected: CPU not stopped"
#define HHCMD036I "TOD clock drag factor = %lf"
#define HHCMD037I "Timer update interval = %d microsecond(s)"
#define HHCMD038I "Restart key depressed"
#define HHCMD039E "Invalid arguments"
#define HHCMD040I "Instruction %s %s %s"
#define HHCMD045I "%1d:%04X attention request raised"
#define HHCMD047E "%1d:%04X attention request rejected"
#define HHCMD049W "Are you sure you didn't mean 'ipl %04X' instead?"
#define HHCMD050I "Interrupt key depressed"
#define HHCMD051I "LOADPARM=%s"
#define HHCMD052E "Processor %s%02X does not allow ipl nor restart"
#define HHCMD053I "SHCMDOPT invalid option: %s"
#define HHCMD054S "DIAG8CMD: %sable, %secho"
#define HHCMD056I "LPAR name = %s"
//#define HHCMD059E in hsccmd.c
#define HHCMD060I "LPAR number = %"I16_FMT"X"
#define HHCMD061E "LPARNUM %02X invalid; must be 00 to 3F (hex)"
#define HHCMD062E "Missing argument(s)"
#define HHCMD066E "Program interrupt number %s is invalid"
#define HHCMD067S "Incorrect keyword %s for the ASN_AND_LX_REUSE statement"
#define HHCMD068E "Invalid value: %s; Enter \"help scsimount\" for assistance"
#define HHCMD069I "%s of %s-labeled volume \"%s\" pending for drive %u:%4.4X = %s"
#define HHCMD072I "Device(%4.4X) synchronous: %12" I64_FMT "d asynchronous: %12" I64_FMT "d"
#define HHCMD073I "No synchronous I/O devices found"
#define HHCMD074I "TOTAL synchronous: %12" I64_FMT "d asynchronous: %12" I64_FMT "d  %3" I64_FMT "d%%"
#define HHCMD075E "Invalid max device threads value (must be -1 to n)"
#define HHCMD076I "Max device threads: %d, current: %d, most: %d, waiting: %d, max exceeded: %d"
#define HHCMD078E "Max device threads %d current %d most %d waiting %d total I/Os queued %d"
#define HHCMD079W "%1d:%04X Only devices on CSS 0 are usable in S/370 mode"
#define HHCMD081E "No cckd devices found"
#define HHCMD084E "%1d:%04X is not a cckd device"
#define HHCMD087E "Operand must be `merge', `nomerge' or `force'"
#define HHCMD088E "Operand must be a number -1 .. 4"
#define HHCMD089E "Unexpected operand: %s"	
#define HHCMD091E "Command must be 'sf+', 'sf-', 'sfc', 'sfk' or 'sfd'"
#define HHCMD093E "Missing argument(s)"
#define HHCMD096E "%1d:%04X busy or interrupt pending"
#define HHCMD098I "%1d:%04X initialized"
#define HHCMD099E "savecore rejected: filename missing"
#define HHCMD100I "pantitle = %s"
#define HHCMD101I "Current message held time is %d seconds"
#define HHCMD102I "Held messages cleared"
#define HHCMD103I "The message held time is set to %d seconds"
#define HHCMD104I "Saving locations %8.8X-%8.8X to %s"
#define HHCMD105E "savecore error creating %s: %s"
#define HHCMD106E "savecore error writing to %s: %s"
#define HHCMD107E "savecore: unable to save %d bytes"
#define HHCMD108E "loadcore rejected: filename missing"
#define HHCMD109E "Cannot open %s: %s"
#define HHCMD110E "Legacysenseid invalid option: %s"
#define HHCMD111I "Legacysenseid %sabled"
#define HHCMD112I "Loading %s to location %x"
#define HHCMD113E "MODEL: no model code"
#define HHCMD114E "PLANT: no plant code"
#define HHCMD115E "MANUFACTURER: no manufacturer code"
#define HHCMD116E "Address greater than mainstore size"
#define HHCMD117E "loadtext rejected: CPU not stopped"
#define HHCMD118E "Cannot open %s: %s"
#define HHCMD119E "Cannot read %s: %s"
#define HHCMD120I "Finished loading TEXT deck file, last 'TXT' record had address: %3.3X"
//#define HHCMD123I in hsccmd.c
#define HHCMD126I "Architecture mode = %s"
#define HHCMD127E "All CPU's must be stopped to change architecture"
#define HHCMD128E "Invalid architecture mode %s"
#define HHCMD130E "Invalid frame address %8.8X"
#define HHCMD131I "Frame %8.8X marked %s"
#define HHCMD134I "CKD KEY trace is now %s"
#define HHCMD136I "CCW tracing is now %s for device %1d:%04X"
#define HHCMD137I "CCW stepping is now %s for device %1d:%04X"
#define HHCMD138E "Unrecognized +/- command"
#define HHCMD146E "Work buffer malloc() failed: %s"
#define HHCMD147W "Warning: not all devices shown (max %d)"
#define HHCMD148E "savecore: no modified storage found"
#define HHCMD150W "evm command is deprecated. Use \"ecpsvm\" instead"
#define HHCMD153I "Processor %s%02X offline"
#define HHCMD156E "CPUIDFMT must be either 0 or 1"
#define HHCMD157I "CPUIDFMT = %d"
#define HHCMD160W "Processor %s%02X not configured"
#define HHCMD161I "%s%7d"
#define HHCMD162E "Invalid format. Enter \"help gpr\" for assistance"
#define HHCMD163E "Invalid format. Command does not support any arguments"
#define HHCMD164E "Invalid format. .Enter \"help cr\" for assistance"
#define HHCMD165E "Invalid operand %s"
#define HHCMD166E "No argument"
#define HHCMD170I "savecore command complete"
#define HHCMD180E "shell commands are disabled"
#define HHCMD181E "%1d:%04X not found"
#define HHCMD182E "Device numbers can only be redefined within the same Logical Channel SubSystem"
#define HHCMD183E "Reinit rejected for drive %u:%4.4X; drive not empty"
#define HHCMD184I "%s"
#define HHCMD187E "Invalid argument"
#define HHCMD188E "Missing arguments; enter 'help tt32' for assistance"
#define HHCMD189I "TT32 debug tracing messages %s"
#define HHCMD190I "Keep-alive = (%d,%d,%d)"
#define HHCMD192E "Invalid format. Enter \"help conkpalv\" for assistance"
#define HHCMD195I "Log options: %s"
#define HHCMD196E "Invalid logopt value %s"
#define HHCMD197I "Log option set: %s"
#define HHCMD200E "Missing operand; enter 'HELP AUTOMOUNT' for assistance"
#define HHCMD202E "Empty list"
#define HHCMD203I "\"%c%s\""
#define HHCMD205E "**LOGIC ERROR** file \"%s\", line %d"
#define HHCMD206E "Out of memory"
#define HHCMD207E "Invalid AUTOMOUNT directory: \"%s\": %s"
#define HHCMD208E "AUTOMOUNT directory \"%s\" conflicts with previous specification"
#define HHCMD209E "AUTOMOUNT directory \"%s\" duplicates previous specification"
#define HHCMD210I "%s%s AUTOMOUNT directory = \"%s\""
#define HHCMD211E "Out of memory"
#define HHCMD212I "Default Allowed AUTOMOUNT directory = \"%s\""
#define HHCMD214I "Ok.%s"
#define HHCMD215E "Out of memory"
#define HHCMD216I "Default Allowed AUTOMOUNT directory = \"%s\""
#define HHCMD217E "Empty list"
#define HHCMD218E "Entry not found"
#define HHCMD219E "Unsupported function; enter 'HELP AUTOMOUNT' for assistance"
#define HHCMD320I "%1d:%04X fcb %s/"
#define HHCMD322E "%1d:%04X is not a 1403 device"
#define HHCMD323E "%1d:%04X not stopped"
#define HHCMD324E "%1d:%04X invalid fcb image ==>%s<=="
//#define HHCMD422I in hscmisc.c
#define HHCMD423E "Script file buffer malloc failed: %s"
#define HHCCP424I "Processor %s%02X store status completed"
#define HHCMD425S "DIAG8CMD invalid option: %s"
#define HHCMD426E "%1d:%04X busy or interrupt pending"
#define HHCMD427E "%1d:%04X subchannel not enabled"
#define HHCMD428E "Target processor %s is invalid"
#define HHCMD429E "Missing argument(s)"
#define HHCMD430E "LPARNUM must be one or two hex digits"
#define HHCMD431E "LCSS id %s is invalid"
#define HHCMD432I "Processor %s%02X online"
#define HHCMD433E "Script file \"%s\" not found"
#define HHCMD434I "Hercules instruction trace displayed in %s mode"
#define HHCHD435E "Usage: %s <path>"
#define HHCHD436I "Module %s unloaded"
#define HHCHD437I "Unloading %s ..."
#define HHCHD438I "Loading %s ..."
#define HHCHD439I "Module %s loaded"
#define HHCHD440E "Usage: %s <module>"
#define HHCMD441S "DEFSYM requires a single value (use quotes if necessary)"
#define HHCMD442E "invalid address: %s"
#define HHCMD443E "loadtext rejected: filename missing"
#define HHCMD444I "%d bytes read from %s"
#define HHCMD445E "loadcore rejected: CPU not stopped"
#define HHCMD446E "invalid address: %s"
#define HHCMD447E "invalid range: %8.8X-%8.8X"
#define HHCMD448E "savecore rejected: CPU not stopped"
#define HHCMD449E "savecore: invalid ending address: %s"
#define HHCMD450E "savecore: invalid starting address: %s"
#define HHCMD451S "%s: %s invalid argument"
#define HHCMD452E "ipl rejected: All CPU's must be stopped"
#define HHCMD453E "System reset/clear rejected: All CPU's must be stopped"
#define HHCMD454E "Missing argument"
#define HHCMD467E "Program interrupt number out of range (%4.4X)"
#define HHCMD497E "Initialization failed for device %1d:%04X"
#define HHCMD800I "Hercules has been up for %u week%s, %u day%s, %02u:%02u:%02u"
#define HHCMD801I "Hercules has been up for %u day%s, %02u:%02u:%02u"
#define HHCMD802I "Hercules has been up for %02u:%02u:%02u"
#define HHCMD820I "SCLPROOT %s"
#define HHCMD821I "SCLP DISK I/O Disabled"
#define HHCMD830I "HTTPROOT %s"
#define HHCMD831I "HTTPROOT not specified"
#define HHCMD832S "HTTP server already active"
#define HHCMD833S "Invalid HTTP port number %s"
#define HHCMD834S "Unrecognized argument %s"
#define HHCMD835S "Cannot create http_server thread: %s"
#define HHCMD836I "HTTPPORT %d"
#define HHCMD837S "Invalid HTTP_SERVER_CONNECT_KLUDGE value: %s"
#define HHCMD838S "HTTP_SERVER_CONNECT_KLUDGE value: %s"
#define HHCMD850I "Tape mount reinit %sallowed"
#define HHCMD851I "Auto SCSI mount %d seconds"
#define HHCMD870I "Instruction counts reset to zero"
#define HHCMD871E "Sorry, not enough memory"
#define HHCMD872E "Sorry, too many instructions"
//#define HHCMD875I in hsccmd.c
//#define HHCMD876I in hsccmd.c
#define HHCMD877I  " i: %12" I64_FMT "d"
#define HHCMD878I "%3d: %12" I64_FMT "d"
#define HHCMD994E "Script aborted : user cancel request"
#define HHCMD996E "The script command requires a filename"
#define HHCMD997E "Only 1 script may be invoked from the panel at any time"
#define HHCMD998E "Script aborted : Script recursion level exceeded"
#define HHCMD999I "Script \"%s\" aborted due to previous conditions"

/* hscmisc.c */
#define HHCIN098I "Shutdown initiated"
#define HHCIN900I "Begin Hercules shutdown"
#define HHCIN901I "Releasing configuration"
#define HHCIN902I "Configuration release complete"
#define HHCIN903I "Calling termination routines"
#define HHCIN904I "All termination routines complete"
#define HHCIN909I "Hercules shutdown complete"
#define HHCMD143E "Invalid value: %s"
#define HHCMD144E "Invalid operand: %s"
#define HHCMD145E "Invalid range: %s"
#define HHCMS001E "malloc failed for REGS copy: %s"

/* hscutl.c */
#define HHCUT001I "SO_KEEPALIVE rc=%d %s"
#define HHCUT002I "TCP_KEEPALIVE rc=%d %s"
#define HHCUT003I "TCP_KEEPIDLE rc=%d %s"
#define HHCUT004I "TCP_KEEPINTVL rc=%d %s"
#define HHCUT005I "TCP_KEEPCNT rc=%d %s"
#define HHCMD042I "%s=%s"

/* httpserv.c */
#define HHCHT001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCHT002E "Socket error: (%s)"
#define HHCHT003W "Waiting for port(%u) to become free"
#define HHCHT004E "Bind error: (%s)"
#define HHCHT005E "Listen error: (%s)"
#define HHCHT006I "Waiting for HTTP requests on port(%u)"
#define HHCHT007E "Select error: (%s)"
#define HHCHT008E "Accept error: (%s)"
#define HHCHT009I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCHT010E "Http_request create_thread error: (%s)"
#define HHCHT011E "Html_include: Cannot open file(%s): (%s)"
#define HHCHT013I "Using HTTPROOT directory (%s)"
#define HHCHT014E "Invalid HTTPROOT: (%s): (%s)"

/* impl.c */
#define HHCIN001S "Cannot register SIGINT handler: %s"
#define HHCIN002E "Cannot suppress SIGPIPE signal: %s"
#define HHCIN003S "Cannot register SIGILL/FPE/SEGV/BUS/USR handler: %s"
#define HHCIN004S "Cannot create HAO thread: %s"
#define HHCIN005S "Cannot create watchdog thread: %s"
#define HHCIN006S "Cannot create shared_server thread: %s"
#define HHCIN007S "Cannot create %4.4X connection thread: %s"
#define HHCIN008S "DYNGUI.DLL load failed; Hercules terminated"
#define HHCIN009S "Cannot register SIGTERM handler: %s"
#define HHCIN010S "Cannot register ConsoleCtrl handler: %s"
#define HHCIN021I "%s Event received, SHUTDOWN %sstarting..."
#define HHCIN022I "Ctrl-C intercepted"
#define HHCIN023W "%s Event received, SHUTDOWN previously requested..."
#define HHCIN050I "Ctrl-Break intercepted. Interrupt Key depressed simulated"
#define HHCIN099I "Hercules terminated"
#define HHCIN950I "Begin system cleanup"
#define HHCIN959I "System cleanup complete"
#define HHCMD995E ".RC file \"%s\" not found"
#define HHCIN999S "Usage: %s [-f config-filename] [-d] [-b logo-filename]%s [> logfile]"

/* ipl.c */
#define HHCCP027E "Device(%4.4X) not in configuration%s"
#define HHCCP029E "Arch mode(%s) IPL failed: CSW status(%2.2X%2.2X) Sense(%s)"
#define HHCCP030E "Arch mode(%s) IPL failed: Invalid IPL PSW(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X)"

/* logger.c */
#define HHCLG014E "Log not active"
#define HHCLG015I "Log closed"
#define HHCLG016E "Error opening logfile(%s) %s"
#define HHCLG017S "Log file(%s) fdopen failed %s"

/* machchk.c */
#define HHCCP017I "Processor(%s%02X) Machine check due to host error(%s)"
#define HHCCP018I "Processor(%s%02X) Check-Stop due to host error: %s"
#define HHCCP019I "Machine Check code(%16.16" I64_FMT "u)"
#define HHCCP020E "Signal USR2 received for undetermined device"
#define HHCCP021E "Signal USR2 received for device(%1d:%04X)"


/* panel.c */
#define HHCPN001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCPN002S "Cannot obtain keyboard buffer: (%s)"
#define HHCPN003S "Cannot obtain message buffer: (%s)"

/* printer.c */
#define HHCPR001E "%1d:%04X File name missing or invalid for printer"
#define HHCPR002E "%1d:%04X Printer(%4.4X) Invalid argument(%s)"
#define HHCPR003E "%1d:%04X Error writing to file(%s) (%s)"
#define HHCPR004E "%1d:%04X Error opening file(%s) (%s)"
#define HHCPR005E "%1d:%04X Initialization error: pipe %s"
#define HHCPR006E "%1d:%04X Initialization error: fork %s"
#define HHCPR007I "%1d:%04X Pipe receiver pid(%d) starting"
#define HHCPR008E "%1d:%04X dup2 error: %s"
#define HHCPR009E "%1d:%04X Parameter(%s) #(%d) is invalid"
#define HHCPR010E "%1d:%04X Parameter(%s) #(%d) pos(%d) is invalid"
#define HHCPR011I "%1d:%04X pipe receiver pid(%d) terminating"
#define HHCPR012E "%1d:%04X Unable to execute file(%s) (%s)"
#define HHCPR015E "%1d:%04X Create spthread failed errno(%d) (%s)"
#define HHCPR016I "%1d:%04X %s (%s) disconnected from device (%s)"
#define HHCPR019E "%1d:%04X Incompatible option(%s) specified"

/* pttrace.c */
#define HHCPT001E "Invalid argument(%s)"
#define HHCPT002E "Trace is busy"
#define HHCPT003I "Ptt(%s%s%s%s%s%s%s%s%s%s%s %s %s) to(%d %d)"

/* scedasd.c */
#define HHCSC001E "Load from file(%s) failed: %s"
#define HHCSC003E "Load from path(%s) failed: %s"
#define HHCSC011E "set_sce_dir: %s: %s"
#define HHCSC012E "set_sce_basedir: %s: %s"
#define HHCSC031E "load_main: %s: %s"
#define HHCSC032W "load_main: terminated at end of mainstor"
#define HHCSC041E "File(%s) open error: %s"
#define HHCSC101E "access error: %s: %s"
#define HHCSC201E "File(%S) access error: %s"

/* scsitape.c */
#define HHCTA300I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTA301I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTA323I "%s"
#define HHCTA324E "%1d:%04X File(%s) Open error; errno(%d): (%s)"
#define HHCTA330E "%1d:%04X File(%s) Error setting attributes; errno(%d): (%s)"
#define HHCTA332E "%1d:%04X File(%s) Error reading data block; errno(%d): (%s)"
#define HHCTA333E "%1d:%04X File(%s) Error writing data block; errno(%d): (%s)"
#define HHCTA334E "%1d:%04X File(%s) Error writing tapemark; errno(%d): (%s)"
#define HHCTA335E "%1d:%04X File(%s) Forward space block error; errno(%d): (%s)"
#define HHCTA336E "%1d:%04X File(%s) Backspace block error; errno(%d): (%s)"
#define HHCTA337E "%1d:%04X File(%s) Forward space file error; errno(%d): (%s)"
#define HHCTA338E "%1d:%04X File(%s) Backspace file error; errno(%d): (%s)"
#define HHCTA373E "%1d:%04X File(%s) Error rewinding; errno(%d): (%s)"
#define HHCTA376E "%1d:%04X File(%s) Error unloading tape; errno(%d): (%s)"
#define HHCTA377I "%1d:%04X File(%s) Tape unloaded"
#define HHCTA380E "%1d:%04X File(%s) Erase gap error; errno(%d): (%s)"
#define HHCTA381E "%1d:%04X File(%s) Data Security Erase error; errno(%d): (%s)"
#define HHCTA382W "%1d:%04X File(%s) ioctl_tape(MTIOCPOS=MTTELL) failed; errno(%d): (%s)"
#define HHCTA383W "%1d:%04X File(%s) ioctl_tape(MTIOCTOP=MTSEEK) failed; errno(%d): (%s)"
#define HHCTA389E "%1d:%04X File(%s) Sync error; errno(%d): (%s)"

/* shared.c */
#define HHCSH001S "Parameter #(%d) is invalid: %s"
#define HHCSH002W "%1d:%04X Connect pending to file(%s)"
#define HHCSH003S "%1d:%04X Error retrieving cylinders"
#define HHCSH004S "%1d:%04X Error retrieving device characteristics"
#define HHCSH005S "%1d:%04X Remote device(%04X) is a %04X"
#define HHCSH006S "%1d:%04X Error retrieving device id"
#define HHCSH007S "%1d:%04X Device type(%04X) not found in dasd table"
#define HHCSH008S "%1d:%04X Control unit(%s) not found in dasd table"
#define HHCSH009I "File(%s) cyls(%d) heads(%d) tracks(%d) trklen(%d)"
#define HHCSH012S "%1d:%04X Error retrieving fba origin"
#define HHCSH013S "%1d:%04X Error retrieving fba number blocks"
#define HHCSH014S "%1d:%04X Error retrieving fba block size"
#define HHCSH019I "File(%s) origin(%d) blks(%d)"
#define HHCSH020E "%1d:%04X Error during channel program start"
#define HHCSH021E "%1d:%04X Error during channel program end"
#define HHCSH022E "%1d:%04X Error reading track(%d)"
#define HHCSH024E "%1d:%04X Error reading block group(%d)"
#define HHCSH026E "%1d:%04X Error retrieving usage information"
#define HHCSH027E "%1d:%04X Error writing track(%d)"
#define HHCSH028E "%1d:%04X Remote error writing track(%d) %2.2X-%2.2X"
#define HHCSH029E "%1d:%04X Socket failed: %s"
#define HHCSH031I "%1d:%04X Connected to file(%s)"
#define HHCSH032E "%1d:%04X Connect to file(%s) errno(%d): %s"
#define HHCSH033E "%1d:%04X send error(%d) for %2.2X-%2.2X: %s"
#define HHCSH034E "%1d:%04X Not connected to file(%s)"
#define HHCSH035E "%1d:%04X recv error(%d): %s"
#define HHCSH036E "%1d:%04X Remote error %2.2X-%2.2X: %s"
#define HHCSH037E "Decompress error(%d) off(%d) len(%d)"
#define HHCSH038E "Data compressed using libz, unsupported"
#define HHCSH040E "Data compressed using bzip2, unsupported"
#define HHCSH041E "%1d:%04X send error(%d) id(%d) %s"
#define HHCSH042W "%1d:%04X busy client being removed id(%d) %s"
#define HHCSH043I "%s disconnected from device(%1d:%04X) id(%d)"
#define HHCSH0474 "Connect to ip(%s) failed"
#define HHCSH053I "Ip(%s) connected to device(%1d:%04X) id(%d)"
#define HHCSH045I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSH046E "Select error: %s"
#define HHCSH047E "%1d:%04X ip(%s) recv error id(%d)"
#define HHCSH048I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSH050E "inet socket: %s"
#define HHCSH051W "unix socket: %s"
#define HHCSH052W "Waiting for port(%u) to become free"
#define HHCSH053E "inet bind: %s"
#define HHCSH054W "unix bind: %s"
#define HHCSH055E "inet listen: %s"
#define HHCSH056W "unix listen: %s"
#define HHCSH057I "Waiting for shared device requests on port(%u)"
#define HHCSH058E "select: %s"
#define HHCSH059E "accept: %s"
#define HHCSH060E "Function malloc() size %d: %s"
#define HHCSH061E "serverConnect create_thread: %s"
#define HHCSH062E "Invalid or missing argument 1"
#define HHCSH063E "Invalid or missing keyword 2"
#define HHCSH064E "Invalid or missing value %s"
#define HHCSH065E "Function calloc() size=%d: %s"
#define HHCSH066E "Invalid or missing keyword(%s)"
#define HHCSH999E "OPTION_SHARED_DEVICES not defined"

/* sie.c */ /* BHe should we calloc the sieregs? Why not statical?? */
#define HHCCP079E "Processor(%s%02X) calloc failed for sie regs: %s"

/* sockdev.c */
#define HHCSD001E "Device(%4.4X) already bound to socket(%s)"
#define HHCSD002E "Device(%4.4X) bind_device malloc() failed"
#define HHCSD003E "Device(%4.4X) bind_device strdup() failed"
#define HHCSD004I "Device(%4.4X) bound to socket(%s)"
#define HHCSD005E "Device(%4.4X) not bound to any socket"
#define HHCSD006E "Client(%s) ip(%s) still connected to device(%4.4X) (%s)"
#define HHCSD007I "Device(%4.4X) unbound from socket(%s)"
#define HHCSD008E "Socket pathname(%s) exceeds limit(%d)"
#define HHCSD009E "Error creating socket(%s) %s"
#define HHCSD010E "Failed to bind or listen on socket(%s) %s"
#define HHCSD011E "Failed to determine IP address from node(%s)"
#define HHCSD012E "Failed to determine port number from service(%s)"
#define HHCSD015E "Client(%s) ip(%s) connection to device(%4.4X) (%s) rejected: device busy or interrupt pending"
#define HHCSD016E "Client(%s) ip(%s) connection to device(%4.4X) (%s) rejected: client(%s) ip(%s) still connected"
#define HHCSD017E "Connect to device(%4.4X) (%s) failed: %s"
#define HHCSD018I "Client(%s) ip(%s) connected to device(%4.4X) (%s)"
#define HHCSD020I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSD021E "select failed; errno(%d) %s"
#define HHCSD022I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSD023E "Cannot create socketdevice thread: errno(%d) %s"
#define HHCSD024E "This build does not support Unix domain sockets"
#define HHCSD025I "Client(%s) ip(%s) disconnected from device(%4.4X) (%s)"
#define HHCSD026E "Client(%s) ip(%s) connection to device(%4.4X) (%s) rejected: by onconnect callback"

/* sr.c */
#define HHCSR001I "Resuming suspended file(%s) created"
#define HHCSR010E "Write error(%s)"
#define HHCSR011E "Read error(%s)"
#define HHCSR012E "Seek error(%s)"
#define HHCSR013E "Value error, incorrect length"
#define HHCSR014E "String error, incorrect length"
#define HHCSR015E "Error processing file(%s)"
#define HHCSR016E "CPU key(%8.8X) found but no active CPU"
#define HHCSR101E "Too many arguments"
#define HHCSR102E "File(%s) open error(%s)"
#define HHCSR103W "Waiting for device(%4.4X)"
#define HHCSR104W "Device(%4.4X) still busy, proceeding anyway"
#define HHCSR105E "Archmode(%s) not supported"
#define HHCSR106E "Mainsize mismatch: %dM expected %dM"
#define HHCSR108E "Storkey size mismatch: %d expected %d"
#define HHCSR110E "Xpndsize mismatch: %dM expected %dM"
#define HHCSR113E "Processor(%s%02X) exceeds max allowed cpu(%02d)"
#define HHCSR114E "Processor(%s%02X) already configured"
#define HHCSR115E "Processor(%s%02X) unable to configure online"
#define HHCSR116E "Processor(%s%02X) invalid psw length(%d)"
#define HHCSR117E "Processor(%s%02X) error loading psw - rc(%d)"
#define HHCSR118W "Device(%4.4X) initialization failed"
#define HHCSR119W "Device(%4.4X) type mismatch; %s expected %s"
#define HHCSR120E "Device(%4.4X) %s size mismatch: %d expected %d"
#define HHCSR132E "Device(%4.4X) type mismatch: %4.4X expected %4.4X"
#define HHCSR133E "Device(%4.4X) Unable to resume suspended device: %s"
#define HHCSR203E "All CPU's must be stopped to resume"
#define HHCSR204E "File identifier error"
#define HHCSR999E "Invalid key %8.8x"

/* tapeccws.c */
#define HHCTA072E "%1d:%04X Data chaining not supported for CCW(%2.2X)"
#define HHCTA081I "%1d:%04X Locate block(0x%8.8"I32_FMT"X) on %s"
#define HHCTA090E "%1d:%04X Tape file(%s) auto-mount failed: (%s)"
#define HHCTA091E "%1d:%04X Tape file(%s) auto-mount rejected: drive not empty"
#define HHCTA092E "%1d:%04X Tape file(%s) auto-unmount failed"
#define HHCTA093I "%1d:%04X Tape file(%s) auto-unmounted"
#define HHCTA094I "%1d:%04X Tape file(%s) auto-mounted"
#define HHCTA099I "%1d:%04X Tape Display(%s) until unmounted"
#define HHCTA199I "%1d:%04X Tape Display(%s) until unmounted, then (%s) until mounted"

/* tapedev.c */
#define HHCTA001E "%1d:%04X Tape file(%s) - format type is not determinable; Internal error: %s error(%s) on index(%d)"
#define HHCTA003W "%1d:%04X Tape file(%s) - format type is not determinable; %s is presumed"
#define HHCTA004I "%1d:%04X Tape file(%s) - format type is %s"
#define HHCTA010I "%1d:%04X Display(%s)"
#define HHCTA066I "%1d:%04X Option(%s) accepted"
#define HHCTA067E "%1d:%04X Option(%s) unrecognized"
#define HHCTA068E "%1d:%04X Option(%s) method must be within(%u-%u)"
#define HHCTA069E "%1d:%04X Option(%s) level must be within(%u-%u)"
#define HHCTA070E "%1d:%04X Option(%s) chunksize must be within(%u-%u)"
#define HHCTA071E "%1d:%04X Option(%s) parse error"
#define HHCTA078E "%1d:%04X Option(%s) not valid for %s"

/* timer.c */
#define HHCTT001W "Timer thread set priority(%d) failed: (%s)"
#define HHCTT002I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTT003I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"

/* tuntap.c */
#define HHCTU001E "Unable to determine operating system type: %s"
#define HHCTU002E "Error opening TUN/TAP device(%s) %s"
#define HHCTU003E "Error setting TUN/TAP mode(%s) %s"
#define HHCTU004E "TUN/TAP device name(%s) invalid"
#define HHCTU005E "Net device name(%s) invalid"
#define HHCTU006E "Net device(%s) ip(%s) invalid"
#define HHCTU008E "Net device(%s) destination address(%s) invalid"
#define HHCTU010E "Net device(%s) net mask(%s) invalid"
#define HHCTU012E "Net device(%s) Invalid null or empty MTU"
#define HHCTU013E "Net device(%s) MTU(%s) invalid"
#define HHCTU015E "Net device(%s) MAC address(%s) invalid"
#define HHCTU020E "Net device(%s) gateway address(%s) invalid"
#define HHCTU025E "Call to socketpair failed: %s"
#define HHCTU026E "Call to fork failed: %s"
#define HHCTU027E "execl error on %s: %s"
#define HHCTU028I "Closing %" I64_FMT "d files"
#define HHCTU029I "Executing '%s' to configure interface"
#define HHCTU030I "IFC_IOCtl called for %s on FDs %d %d"
#define HHCTU031E "%s timeout, possible older version"

/* version.c */
#define HHCIN010I "%sversion (%s)"
#define HHCIN011I "%s"
#define HHCIN012I "Built on (%s) at (%s)"
#define HHCIN013I "Build information:"
#define HHCIN014I "%s"

/* vm.c */
#define HHCVM001I "Panel command *%s* issued by guest %s"
#define HHCVM005W "Panel command *%s* issued by guest not processed, disabled in configuration"

/* vmd250.c */
#define HHCVM006E "VM BLOCK I/O environment malloc failed"
#define HHCVM007I "Device(%4.4X) d250_init BLKTAB: type(%4.4X) arch(%i) 512(%i) 1024(%i) 2048(%i) 4096(%i)"
#define HHCVM008I "Device(%4.4X) d250_init32 s(%i) o(%i) b(%i) e(%i)"
#define HHCVM009E "d250_list32 error: PSC(%i)"
#define HHCVM010E "Device(%4.4X) Block I/O create_thread error %s"
#define HHCVM011E "VM BLOCK I/O request malloc failed"
#define HHCVM012I "Device(%4.4X) d250_preserve pending sense preserved"
#define HHCVM013I "Device(%4.4X) d250_restore pending sense restored"
#define HHCVM014I "Device(%4.4X) d250_list32 BIOE(%8.8X) status(%2.2X)"
#define HHCVM015I "Device(%4.4X) d250_list32 BIOEs(%i) A("F_RADR") I/O key(%2.2X)"
#define HHCVM016I "Device(%4.4X) d250_list32 BIOE(%8.8X) oper(%2.2X) block(%i) buffer(%8.8X)"
#define HHCVM017I "Device(%4.4X) d250_iorq32 PSC(%d) succeeded(%d) failed(%d)"
#define HHCVM018I "Device(%4.4X) d250_read %d-byte block (rel. to 0): %d"
#define HHCVM019I "Device(%4.4X) ASYNC BIOEL(%8.8X) Entries(%d) Key(%2.2X) Intp(%8.8X)"
#define HHCVM020I "Device(%4.4X) d250_list32 xcode(%4.4X) BIOE32(%8.8X-%8.8X) FETCH key(%2.2X)"
#define HHCVM021I "Device(%4.4X) d250_read FBA unit status(%2.2X) residual(%d)"
#define HHCVM022I "Device(%4.4X) d250_remove Block I/O environment removed"
#define HHCVM023I "Device(%4.4X) Triggered Block I/O interrupt: code(%4.4X) parm(%16.16X) status(%2.2X) subcode(%2.2X)"
#define HHCVM109E "d250_list64 error: PSC(%i)"
#define HHCVM110E "Device(%4.4X) create_thread error: %s"
#define HHCVM114I "Device(%4.4X) d250_list64 BIOE(%16.16X) status(%2.2X)"
#define HHCVM115I "Device(%4.4X) d250_list64 BIOEs(%i) A("F_RADR" I/O key(%2.2X)"
#define HHCVM116I "Device(%4.4X) d250_list64 BIOE(%16.16X) oper(%2.2X) block(%i) buffer(%16.16X)"
#define HHCVM117I "Device(%4.4X) d250_iorq64 PSC(%d) succeeded(%d) failed(%d)"
#define HHCVM119I "Device(%4.4X) d250_iorq32 SYNC BIOEL(%8.8X) Entries(%d) Key(%2.2X)"
#define HHCVM120I "Device(%4.4X) d250_list32 xcode(%4.4X) Rd Buf(%8.8X-%8.8X) FETCH key(%2.2X)"
#define HHCVM219I "Device(%4.4X) ASYNC BIOEL(%16.16X) Entries(%d) Key(%2.2X) Intp(%16.16X)"
#define HHCVM220I "Device(%4.4X) d250_list32 xcode(%4.4X) Wr Buf(%8.8X-%8.8X) STORE key(%2.2X)"
#define HHCVM319I "Device(%4.4X) d250_iorq64 SYNC BIOEL(%16.16X) Entries9%d) Key(%2.2X)"
#define HHCVM320I "Device(%4.4X) d250_list32 xcode(%4.4X) Status(%8.8X-%8.8X) STORE key(%2.2X)"
#define HHCVM420I "Device(%4.4X) d250_list64 xcode(%4.4X) BIOE64(%8.8X-%8.8X) FETCH key(%2.2X)"
#define HHCVM520I "Device(%4.4X) d250_list64 xcode(%4.4X) Rd Buf(%16.16X-%16.16X) FETCH key(%2.2X)"
#define HHCVM620I "Device(%4.4X) d250_list64 xcode(%4.4X) Wr Buf(%16.16X-%16.16X) STORE key(%2.2X)"
#define HHCVM720I "Device(%4.4X) d250_list64 xcode(%4.4X) Status(%16.16X-%16.16X) STORE key(%2.2X)"

/* w32chan.c */
#define HHCWN084E "Device(%4.4X) malloc(DEVIOREQUEST) failed; strerror=\"%s\""
#define HHCWN085W "Exceeded maximum device threads; devtmax=%d"
#define HHCWN086E "Device(%4.4X) malloc(DEVTHREADPARMS) failed; strerror=\"%s\""
#define HHCWN087E "Device(%4.4X) CreateEvent(hShutdownEvent) failed; strerror=\"%s\""
#define HHCWN088E "Device(%4.4X) CreateEvent(hRequestQueuedEvent) failed; strerror=\"%s\""
#define HHCWN089E "Device(%4.4X) fthread_create(DeviceThread) failed; strerror=\"%s\""

/* w32ctca.c */
#define HHCWC100I "%s version %s initiated"
#define HHCWC120E "** tt32_loaddll: One of the GetProcAddress calls failed" 
#define HHCWC121E "** tt32_loaddll: LoadLibraryEx(\"%s\") failed; rc=%ld: %s"
#define HHCWC199D "%s"
