/* MSGENU.H     (c) Copyright Bernard van der Helm, 2010             */
/*              Header file for Hercules messages (US English)       */

/* Message text (c) Copyright Roger Bowler and others, 1999-2010     */

// $Id$ 

/*-------------------------------------------------------------------*/
/* This file contains the text of all of the messages issued by      */
/* the various components of the Hercules mainframe emulator.        */
/*-------------------------------------------------------------------*/

#define MSG(id, ...)      #id " " id "\n", ## __VA_ARGS__
#define WRITEMSG(id, ...) logmsg(#id " " id "\n", ## __VA_ARGS__)
#define WRITECMSG(c, id, ...) logmsg(c #id " " id "\n", ## __VA_ARGS__)
//#define WRITEMSG(id, ...) logmsg("%-10s(%5d) " #id " " id "\n", __FILE__, __LINE__, ## __VA_ARGS__)
//#define WRITECMSG(c, id, ...) logmsg(c "%-10s(%5d) " #id " " id "\n", __FILE__, __LINE__, ## __VA_ARGS__)

/* awstape.c */
#define HHCTA101I "Device(%4.4X): AWS Tape file(%s) closed"
#define HHCTA102E "Device(%4.4X): Error opening file(%s): (%s)"
#define HHCTA103E "Device(%4.4X): Error seeking to offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA104E "Device(%4.4X): Error reading block header at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA105E "Device(%4.4X): End of file (end of tape) at offset("I64_FMTX") in file(%s)"
#define HHCTA106E "Device(%4.4X): Unexpected end of file in block header at offset("I64_FMTX") in file(%s)"
#define HHCTA107E "Device(%4.4X): Block length(%d) exceeds at offset("I64_FMTX") in file(%s)"
#define HHCTA108E "Device(%4.4X): Invalid tapemark at offset("I64_FMTX") in file(%s)"
#define HHCTA109E "Device(%4.4X): Error reading data block at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA110E "Device(%4.4X): Unexpected end of file in data block at offset("I64_FMTX") in file(%s)"
#define HHCTA111E "Device(%4.4X): Error seeking to offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA112E "Device(%4.4X): Media full condition reached at offset("I64_FMTX") in file(%s)"
#define HHCTA113E "Device(%4.4X): Error writing block header at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA114E "Device(%4.4X): Media full condition reached at offset("I64_FMTX") in file(%s)"
#define HHCTA115E "Device(%4.4X): Error writing data block at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA116E "Device(%4.4X): Error writing data block at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA117E "Device(%4.4X): Error seeking to offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA118E "Device(%4.4X): Error writing block header at offset("I64_FMTX") in file (%s): (%s)"
#define HHCTA119E "Device(%4.4X): Error writing tape mark at offset("I64_FMTX") in file(%s): (%s)"
#define HHCTA120E "Device(%4.4X): Sync error on file(%s): (%s)"

/* bldcfg.c */
#define HHCCF001S "Error reading file(%s) line(%d): (%s)"
#define HHCCF002S "File(%s) line(%d) is too long"
#define HHCCF003S "Open error file(%s): (%s)"
#define HHCCF004S "No device records in file(%s)"
#define HHCCF008E "Error in file(%s) line(%d): Syntax error:(%s)"
#define HHCCF009E "Error in file(%s) line(%d): Incorrect number of operands"
#define HHCCF012S "Error in file(%s) line(%d): (%s) is not a valid CPU (%s)"
#define HHCCF013S "Error in file(%s) line(%d): Invalid main storage size (%s)"
#define HHCCF014S "Error in file(%s) line(%d): Invalid expanded storage size (%s)"
#define HHCCF016S "Error in file(%s) line(%d): Invalid (%s) thread priority (%s)"
#define HHCCF017W "Hercules is not running as setuid root, cannot raise (%s) thread priority"
#define HHCCF018S "Error in file(%s) line(%d): Invalid number of CPUs (%s)"
#define HHCCF019S "Error in file(%s) line(%d): Invalid number of VFs (%s)"
#define HHCCF020W "Vector Facility support not configured"
#define HHCCF022S "Error in file(%s) line(%d): (%s) is not a valid system epoch. The only valid values are 1801-2099"
#define HHCCF023S "Error in file(%s) line(%d): (%s) is not a valid timezone offset"
#define HHCCF029S "Error in file(%s) line(%d): Invalid SHRDPORT port number (%s)"
#define HHCCF031S "Cannot obtain (%d)MB main storage: (%s)"
#define HHCCF032S "Cannot obtain storage key array: (%s)"
#define HHCCF033S "Cannot obtain (%d)MB expanded storage: (%s)"
#define HHCCF034W "Expanded storage support not installed"
#define HHCCF035S "Error in file(%s) line(%d): Missing device number or device type"
#define HHCCF036S "Error in file(%s) line(%d): (%s) is not a valid device number(s) specification"
#define HHCCF051S "Error in file(%s) line(%d): (%s) is not a valid serial number"
#define HHCCF052W "Warning in file(%s) line(%d): Invalid ECPSVM level value: (%s), 20 Assumed"
#define HHCCF053W "Error in file(%s) line(%d): Invalid ECPSVM keyword: (%s), NO Assumed"
#define HHCCF061W "Warning in file(%s) line(%d): (%s) statement deprecated. Use (%s) instead"
#define HHCCF062W "Warning in file(%s) line(%d): Missing ECPSVM level value, 20 Assumed"
#define HHCCF063W "Warning in file(%s) line(%d): Specifying ECPSVM level directly is deprecated. Use the 'LEVEL' keyword instead"
#define HHCCF064W "Hercules set priority (%d) failed: (%s)"
#define HHCCF065I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCF070S "Error in file(%s) line(%d): (%s) is not a valid year offset"
#define HHCCF072W "SYSEPOCH (%04d) is deprecated, please specify \"SYSEPOCH 1900 (%s%d)\""
#define HHCCF073W "SYSEPOCH (%04d) is deprecated, please specify \"SYSEPOCH 1960 (%s%d)\""
#define HHCCF074S "Error in file(%s) line(%d): Invalid engine syntax (%s)"
#define HHCCF075S "Error in file(%s) line(%d): Invalid engine type (%s)"
#define HHCCF077I "Engine (%d) set to type (%d) (%s)"
#define HHCCF081I "File(%s) will ignore include errors"
#define HHCCF082S "Error in file(%s) line(%d): Maximum nesting level (%d) reached"
#define HHCCF083I "File(%s) including(%s) at (%d)"
#define HHCCF084W "File(%s) open error ignored file(%s): (%s)"
#define HHCCF085S "File(%s) open error file(%s): (%s)"
#define HHCCF086S "Error in file(%s): NUMCPU(%d) must not exceed MAXCPU(%d)"
#define HHCCF090I "Default Allowed AUTOMOUNT directory = (%s)"
#define HHCCF900S "Out of memory"

/* cache.c */
#define HHCCH001E "Calloc failed cache[%d] size(%d): (%s)"
#define HHCCH002W "Realloc increase failed cache[%d] size(%d): (%s)"
#define HHCCH003W "Realloc decrease failed cache[%d] size(%d): (%s)"
#define HHCCH004W "Buf calloc failed cache[%d] size(%d): (%s)"
#define HHCCH005W "Releasing inactive buffer space"
#define HHCCH006E "Unable to calloc buf cache[%d] size(%d): (%s)"

/* cardpch.c */
#define HHCPU004E "Error writing to file(%s): (%s)"
#define HHCPU001E "File name missing or invalid"
#define HHCPU002E "Invalid argument: (%s)"
#define HHCPU003E "Error opening file(%s): (%s)"

/* cardrdr.c */
#define HHCRD001E "Out of memory"
#define HHCRD002E "File name(%s) too long, max is (%ud)"
#define HHCRD003E "Unable to access file(%s): (%s)"
#define HHCRD004E "Out of memory"
#define HHCRD005E "Specify 'ascii' or 'ebcdic' (or neither) but not both"
#define HHCRD006E "Only one filename (sock_spec) allowed for socket devices"
#define HHCRD007I "Defaulting to 'ascii' for socket device(%4.4X)"
#define HHCRD008W "'multifile' option ignored: only one file specified"
#define HHCRD009E "File name(%s) too long, max is (%ud)"
#define HHCRD010E "Unable to access file(%s): (%s)"
#define HHCRD011E "Close error on file(%s): (%s)"
#define HHCRD012I "%s (%s) disconnected from device(%4.4X) (%s)"
#define HHCRD013E "Error opening file(%s): (%s)"
#define HHCRD014E "Error reading file(%s): (%s)"
#define HHCRD015E "Seek error in file(%s): (%s)"
#define HHCRD016E "Error reading file(%s): (%s)"
#define HHCRD017E "Unexpected end of file(%s)"
#define HHCRD018E "Error reading file(%s): (%s)"
#define HHCRD019E "Card image exceeds (%d) bytes in file(%s)"

/* cckddasd.c */
#define HHCCD001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD002I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD003I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD011I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD012I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD013I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCD092I "%d devices processed"
#define HHCCD101E "Device(%4.4X) error initializing shadow files"
#define HHCCD102E "Device(%4.4X) file[%d] get space error, size exceeds %lldM"
#define HHCCD110E "Device(%4.4X) file[%d] devhdr id error"
#define HHCCD121E "Device(%4.4X) file[%d] trklen err for %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD122E "Device(%4.4X) file[%d] invalid byte 0 trk(%d) buf(%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD123E "Device(%4.4X) file[%d] invalid byte 0 blkgrp(%d) buf(%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD124E "Device(%4.4X) file[%d] invalid %s hdr %s %d: %s compression unsupported"
#define HHCCD125E "Device(%4.4X) file[%d] invalid %s hdr %s %d buf(%p:%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD130E "Device(%4.4X) file[%d] %s open error: %s"
#define HHCCD131E "Device(%4.4X) file[%d] close error: %s"
#define HHCCD132E "Device(%4.4X) file[%d] lseek error, offset 0x%" I64_FMT "x: %s"
#define HHCCD133E "Device(%4.4X) file[%d] read error, offset 0x%" I64_FMT "x: %s"
#define HHCCD134E "Device(%4.4X) file[%d] read incomplete, offset 0x%" I64_FMT "x: read %d expected %d"
#define HHCCD135E "Device(%4.4X) file[%d] lseek error, offset 0x%" I64_FMT "x: %s"
#define HHCCD136E "Device(%4.4X) file[%d] write error, offset 0x%" I64_FMT "x: %s"
#define HHCCD137E "Device(%4.4X) file[%d] write incomplete, offset 0x%" I64_FMT "x: wrote %d expected %d"
#define HHCCD138E "Device(%4.4X) file[%d] ftruncate error, offset 0x%" I64_FMT "x: %s"
#define HHCCD139E "Device(%4.4X) malloc error, size(%d) %s"
#define HHCCD140E "Device(%4.4X) calloc error, size(%d) %s"
#define HHCCD142E "Device(%4.4X) file[%d] shadow file name(%s) collides with %4.4X file[%d] name(%s)"
#define HHCCD151E "Device(%4.4X) file[%d] error re-opening %s readonly: %s"
#define HHCCD160E "Device(%4.4X) not a cckd device"
#define HHCCD161E "Device(%4.4X) file[%d] no shadow file name"
#define HHCCD162E "Device(%4.4X) file[%d] max shadow files exceeded"
#define HHCCD163E "Device(%4.4X) file[%d] error adding shadow file"
#define HHCCD164I "Device(%4.4X) file[%d] %s added"
#define HHCCD165W "Device(%4.4X) error adding shadow file, sf command busy on device"
#define HHCCD170E "Device(%4.4X) not a cckd device"
#define HHCCD171E "Device(%4.4X) file[%d] cannot remove base file"
#define HHCCD172E "Device(%4.4X) file[%d] not merged, file[%d] cannot be opened read-write%s"
#define HHCCD173E "Device(%4.4X) file[%d] not merged, file[%d] check failed"
#define HHCCD174E "Device(%4.4X) file[%d] not merged, file[%d] not hardened"
#define HHCCD175W "Device(%4.4X) file[%d] merge failed, sf command busy on device"
#define HHCCD179I "Merging device(%d:%4.4X)"
#define HHCCD180E "Device(%4.4X) file[%d] not merged, error during merge"
#define HHCCD181I "Device(%4.4X) shadow file [%d] successfully %s"
#define HHCCD182E "Device(%4.4X) file[%d] not merged, error processing trk(%d)"
#define HHCCD190E "Device(%4.4X) file[%d] offset 0x%" I64_FMT "x unknown space(%2.2x%2.2x%2.2x%2.2x%2.2x)"
#define HHCCD193E "Device(%4.4X) file[%d] uncompress error trk(%d) %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCCD194E "Device(%4.4X) file[%d] %s compression not supported"
#define HHCCD200I "Compressing device(%d:%4.4X)"
#define HHCCD201I "Checking device(%d:%4.4X) level(%d)"
#define HHCCD202W "Device(%4.4X) file[%d] check failed, sf command busy on device"
#define HHCCD205W "Device(%4.4X) is not a cckd device"
#define HHCCD206W "Device(%4.4X) file[%d] compress failed, sf command busy on device"
#define HHCCD207I "Adding device(%d:%4.4X)"
#define HHCCD208I "Displaying device(%d:%4.4X)"
#define HHCCD209W "Device(%4.4X) is not a cckd device"
#define HHCCD210I "          size free  nbr st   reads  writes l2reads    hits switches"
#define HHCCD211I "                                                 readaheads   misses"
#define HHCCD212I "--------------------------------------------------------------------"
#define HHCCD213I "[*] %10" I64_FMT "d %3" I64_FMT "d%% %4d    %7d %7d %7d %7d  %7d"
#define HHCCD214I "                                                    %7d  %7d"
#define HHCCD215I "%s"
#define HHCCD216I "[0] %10" I64_FMT "d %3" I64_FMT "d%% %4d %s %7d %7d %7d"
#define HHCCD217I "%s"
#define HHCCD218I "[%d] %10" I64_FMT "d %3" I64_FMT "d%% %4d %s %7d %7d %7d"
#define HHCCD900I "print_itrace"

/* channel.c */
#define HHCCP048I "Device(%4.4X) CCW(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X%s)"
#define HHCCP049I "Device(%4.4X) Stat(%2.2X%2.2X) Count(%2.2X%2.2X) CCW(%2.2X%2.2X%2.2X)"
#define HHCCP050I "Device(%4.4X) SCSW(%2.2X%2.2X%2.2X%2.2X) Stat(%2.2X%2.2X) Count(%2.2X%2.2X) CCW(%2.2X%2.2X%2.2X%2.2X)"
#define HHCCP051I "Device(%4.4X) Test I/O"
#define HHCCP052I "TIO modification executed CC=1"
#define HHCCP053I "Device(%4.4X) Halt I/O"
#define HHCCP054I "HIO modification executed CC=1"
#define HHCCP055I "Device(%4.4X) Clear subchannel"
#define HHCCP056I "Device(%4.4X) Halt subchannel"
#define HHCCP057I "Device(%4.4X) Halt subchannel: cc=%d"
#define HHCCP060I "Device(%4.4X) Resume subchannel: cc=%d"
#define HHCCP078I "Device(%4.4X) MIDAW(%2.2X %4.4"I16_FMT"X %16.16"I64_FMT"X): %s"
#define HHCCP063I "Device(%4.4X) IDAW(%8.8"I32_FMT"X) Len(%3.3"I16_FMT"X): %s"
#define HHCCP064I "Device(%4.4X) IDAW(%16.16"I64_FMT"X) Len(%4.4"I16_FMT"X): %s"
#define HHCCP065I "Device(%4.4X) attention signalled"
#define HHCCP066I "Device(%4.4X) attention"
#define HHCCP067E "Device(%4.4X) create_thread error: %s"
#define HHCCP069I "Device(%4.4X) initial status interrupt"
#define HHCCP070I "Device(%4.4X) attention completed"
#define HHCCP071I "Device(%4.4X) clear completed"
#define HHCCP072I "Device(%4.4X) halt completed"
#define HHCCP073I "Device(%4.4X) suspended"
#define HHCCP074I "Device(%4.4X) resumed"
#define HHCCP075I "Device(%4.4X) Stat(%2.2X%2.2X) Count(%4.4X) %s"
#define HHCCP076I "Device(%4.4X) Sense(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X)"
#define HHCCP077I "Device(%4.4X) Sense(%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s)"

/* ckddasd.c */
#define HHCDA001E "File name missing or invalid"
#define HHCDA002E "Device(%4.4X) File(%s) not found or invalid"
#define HHCDA003E "Parameter(%s) number(%d) is invalid"
#define HHCDA004I "Opening file(%s) readonly%s"
#define HHCDA005E "File(%s) open error(%s)"
#define HHCDA006E "File(%s) not in a single file for shadowing"
#define HHCDA007E "File(%s) fstat error(%s)"
#define HHCDA008E "File(%s) read error(%s)"
#define HHCDA009E "File(%s) CKD header incomplete"
#define HHCDA010E "File(%s) CKD header invalid"
#define HHCDA011E "File(%s) Only 1 CCKD file allowed"
#define HHCDA012E "File(%s) read error(%s)"
#define HHCDA013E "File(%s) CCKD header incomplete"
#define HHCDA014E "File(%s) CKD file out of sequence"
#define HHCDA015I "File(%s) seq(%d) cyls(%d-%d)"
#define HHCDA016E "File(%s) heads(%d) trklen(%d), expected heads(%d) trklen(%d)"
#define HHCDA017E "File(%s) CKD header inconsistent with file size"
#define HHCDA018E "File(%s) CKD header high cylinder incorrect"
#define HHCDA019E "File(%s) exceeds maximum CKD files(%d)"
#define HHCDA020I "File(%s) cyls(%d) heads(%d) tracks(%d) trklen(%d)"
#define HHCDA021E "Device(%4.4X) device type(%4.4X) not found in dasd table"
#define HHCDA022E "Device(%4.4X) control unit(%s) not found in dasd table"
#define HHCDA023I "Device(%4.4X) cache hits(%d), misses(%d), waits(%d)"
#define HHCDA024I "Read trk(%d) cur trk(%d)"
#define HHCDA025I "Read track: updating track(%d)"
#define HHCDA026E "Error writing trk(%d): lseek error(%s)"
#define HHCDA027E "Error writing trk(%d): write error(%s)"
#define HHCDA028I "Read trk(%d) cache hit, using cache[%d]"
#define HHCDA029I "Read trk(%d) no available cache entry, waiting"
#define HHCDA030I "Read trk(%d) cache miss, using cache[%d]"
#define HHCDA031I "Read trk(%d) reading file(%d) offset(%" I64_FMT "d) len(%d)"
#define HHCDA032E "Error reading trk(%d): lseek error(%s)"
#define HHCDA033E "Error reading trk(%d): read error(%s)"
#define HHCDA034I "Read trk(%d) trkhdr(%2.2x %2.2x%2.2x %2.2x%2.2x)"
#define HHCDA035E "Device(%4.4X) invalid track header for cyl(%d) head(%d) %2.2x%2.2x%2.2x%2.2x%2.2x"
#define HHCDA038I "Seeking to cyl(%d) head(%d)"
#define HHCDA039E "MT advance error: locate record(%d) file mask(%2.2X)"
#define HHCDA040I "MT advance to cyl(%d) head(%d)"
#define HHCDA041I "Read count orientation(%s)"
#define HHCDA042E "Attempt to read past end of track(%d %d)"
#define HHCDA043I "Cyl(%d) head(%d) record(%d) kl(%d) dl(%d) of(%d)"
#define HHCDA044I "Read key %d bytes"
#define HHCDA045I "Read data %d bytes"
#define HHCDA046E "Attempt to read past end of track"
#define HHCDA047I "Writing cyl(%d) head(%d) record(%d) kl(%d) dl(%d)"
#define HHCDA048I "Setting track overflow flag for cyl(%d) head(%d) record(%d)"
#define HHCDA049E "Write KD orientation error"
#define HHCDA050I "Updating cyl(%d) head(%d) record(%d) kl(%d) dl(%d)"
#define HHCDA051E "Write data orientation error"
#define HHCDA052I "Updating cyl(%d) head(%d) record(%d) dl(%d)"
#define HHCDA053E "Data chaining not supported for CCW(%2.2X)"
#define HHCDA054I "Set file mask(%2.2X)"
#define HHCDA055I "Search key(%s)"

/* cmdtab.c */
#define HHCPN139E "Command(%s) not found, enter '?' for list"
#define HHCPN140I "Valid panel commands are\n  %-9.9s    %s \n  %-9.9s    %s "
#define HHCPN142I "Command(%s) not found - no help available"

/* codepage.c */
#define HHCCF072I "Using %s codepage conversion table %s"
#define HHCCF051E "Codepage conversion table %s is not defined"

/* comm3705.c and commadpt.c */
#define HHCCA001I "Client(%s) connected to %4.4X device(%4.4X)"
#define HHCCA002I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCA003E "Device(%4.4X) Cannot obtain socket for incoming calls: %s"
#define HHCCA004W "Device(%4.4X) Waiting 5 seconds for port(%d) to become available"
#define HHCCA005I "Device(%4.4X) Listening on port(%d) for incoming TCP connections"
#define HHCCA006T "Device(%4.4X) Select failed: %s"
#define HHCCA007W "Device(%4.4X) Outgoing call failed during %s command: %s"
#define HHCCA008I "Device(%4.4X) Incoming Call"
#define HHCCA009I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCCA010I "device(%4.4X) initialisation not performed"
#define HHCCA011E "Device(%4.4X) Error parsing %s"
#define HHCCA012E "Device(%4.4X) Unrecognized parameter(%s)"
#define HHCCA013E "Device(%4.4X) Incorrect %s specification %s"
#define HHCCA014E "Device(%4.4X) Incorrect switched/dial specification(%s): defaulting to DIAL=OUT"
#define HHCCA015E "Device(%4.4X) Missing parameter: DIAL(%s) and %s not specified"
#define HHCCA016W "Device(%4.4X) Conflicting parameter: DIAL(%s) and %s=%s specified"
#define HHCCA017I "Device(%4.4X) RPORT parameter ignored"
#define HHCCA018E "Device(%4.4X) Bind failed: %s"
#define HHCCA019E "Device(%4.4X) BSC comm thread did not initialise"
#define HHCCA020E "Device(%4.4X) Memory allocation failure for main control block"
#define HHCCA021I "Device(%4.4X) Initialisation failed due to previous errors"
#define HHCCA022E "Cannot create commadpt thread: %s"
#define HHCCA023I "Device(%4.4X) Connect out to %s:%d failed during initial status: %s"

/* con1052c.c */
#define HHC1C001A "Enter input for console device(%4.4X)"

/* config.c */
#define HHCCF040E "Cannot create processor(%s%02X) thread: %s"
#define HHCCF041E "Device(%d:%4.4X) already exists"
#define HHCCF042E "Devtyp(%s) not recognized"
#define HHCCF043E "Cannot obtain device block: %s"
#define HHCCF044E "Initialization failed for device(%4.4X)"
#define HHCCF045E "Cannot obtain buffer for device(%4.4X): %s"
#define HHCCF046E "%s(%d:%4.4X) does not exist"
#define HHCCF047I "%s(%d:%4.4X) detached"
#define HHCCF048E "Device(%d:%4.4X) does not exist"
#define HHCCF049E "Device(%d:%4.4X) already exists"
#define HHCCF053E "Incorrect second device number in device range near character(%c)"
#define HHCCF054E "Incorrect Device count near character(%c)"
#define HHCCF055E "Incorrect device address specification near character(%c)"
#define HHCCF056E "Incorrect device address range(%4.4X < %4.4X)"
#define HHCCF057E "Device(%4.4X_ is on wrong channel (1st device defined on channel(%2.2X))"
#define HHCCF058E "Some or all devices in %4.4X-%4.4X duplicate devices already defined"
#define HHCCF074E "Unspecified error occured while parsing Logical Channel Subsystem Identification"
#define HHCCF075E "No more than 1 Logical Channel Subsystem Identification may be specified"
#define HHCCF076E "Non numeric Logical Channel Subsystem Identification(%s)"
#define HHCCF077E "Logical Channel Subsystem Identification(%d) exceeds maximum(%d)"

/* console.c and comm3705.c */
#define HHCGI001I "Unable to determine IP address from (%s)"
#define HHCGI002I "Unable to determine port number from (%s)"
#define HHCGI003E "Invalid parameter(%s)"

#define HHCTE001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTE002W "Waiting for port(%u) to become free"
#define HHCTE003I "Waiting for console connection on port(%u)"
#define HHCTE004I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)" 
#define HHCTE005E "Cannot create console thread: (%s)"
#define HHCTE007I "Device(%4.4X): Devtype(%4.4X) client(%s) connection closed"
#define HHCTE008I "Device(%4.4X): Connection closed by client(%s)"
#define HHCTE009I "Client(%s) connected to device(%d:%4.4X) devtype(%4.4X)"
#define HHCTE010E "CNSLPORT statement invalid: (%s)"
#define HHCTE011E "Device(%4.4X): Invalid IP address: (%s)"
#define HHCTE012E "Device(%4.4X): Invalid mask value: (%s)"
#define HHCTE013E "Device(%4.4X): Extraneous argument(s): (%s)..."
#define HHCTE014I "Device(%4.4X): Devtype(%4.4X) client(%s) connection reset"
#define HHCTE017E "Device(%4.4X): Duplicate SYSG console definition"
#define HHCTE090E "Device(%4.4X): Malloc() failed for resume buf: (%s)"

/* cpu.c */
#define HHCCP001W "Processor(%s%02X) thread set priority(%d) failed: (%s)"
#define HHCCP002I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(processor %s%02X)"
#define HHCCP003I "Processor(%s%02X) architecture mode(%s)"
#define HHCCP004I "Processor(%s%02X) Vector Facility online"
#define HHCCP006S "Cannot create timer thread: (%s)"
#define HHCCP007I "Processor(%s%02X) architecture mode(%s) set"
#define HHCCP008I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(processor %s%02X)"
#define HHCCP010I "Processor(%s%02X) store status completed"
#define HHCCP011I "Processor(%s%02X) disabled wait state(%s)"
#define HHCCP014I "%s%s%s%02X: (%s) code(%4.4X) ilc(%d%s)"
#define HHCCP015I "Processor(%s%02X) PER event: code(%4.4X) perc(%2.2X) addr(" F_VADR ")"
#define HHCCP016I "Processor(%s%02X) Program interrupt loop: PSW(%s)"
#define HHCCP022I "Machine Check code (%16.16" I64_FMT "u)"
#define HHCCP043I "Wait state PSW loaded: (%s)"
#define HHCCP044I "I/O interrupt code(%4.4X) CSW(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X)"
#define HHCCP045I "I/O interrupt code(%8.8X) parm(%8.8X)"
#define HHCCP046I "I/O interrupt code(%8.8X0 parm(%8.8X), id(%8.8X)"
#define HHCCP080E "Processor(%s%02X) malloc failed for archjmp regs: (%s)"

/* crypto/dyncrypt.c */
#define HHCRY001I "Crypto module loaded (c) Copyright Bernard van der Helm, 2003-2010"
#define HHCRY002I "Active: %s"

/* ctc_ctci.c */
#define HHCCT037E "Device(%4.4X) Unable to allocate CTCBLK"
#define HHCCT040I "Device(%4.4X) Halt or Clear Recognized"
#define HHCCT041I "Device(%4.4X) CTC Received Frame (%d bytes)"
#define HHCCT042E "Device(%4.4X) Write CCW count(%u) is invalid"
#define HHCCT043I "Device(%4.4X) Interface command: %s %8.8X"
#define HHCCT044E "Device(%4.4X) Write buffer contains incomplete segment header at offset(%4.4X)"
#define HHCCT045E "Device(%4.4X) Write buffer contains invalid segment length(%u) at offset(%4.4X)"
#define HHCCT046I "Device(%4.4X) Sending packet to device(%s)"
#define HHCCT047E "Device(%4.4X) Error writing to device(%s): %s"
#define HHCCT048E "Device(%4.4X) Error reading from device(%s): %s"
#define HHCCT049I "Device(%4.4X) Received packet from device(%s) (%d bytes)"
#define HHCCT056E "Device(%4.4X) Incorrect number of parameters"
#define HHCCT050E "Device(%4.4X) Invalid adapter address(%s)"
#define HHCCT051E "Device(%4.4X) Invalid device name(%s)"
#define HHCCT052E "Device(%4.4X) Invalid kernel buffer size(%s)"
#define HHCCT053E "Device(%4.4X) Invalid DLL I/O buffer size(%s)"
#define HHCCT054E "Device(%4.4X) Invalid MTU size(%s)"
#define HHCCT055E "Device(%4.4X) Invalid netmask(%s)"
#define HHCCT056E "Device(%4.4X) Incorrect number of parameters"
#define HHCCT057E "Device(%4.4X) Invalid MAC address(%s)"
#define HHCCT058E "Device(%4.4X) Invalid IP address(%s)"
#define HHCCT061E "Device(%4.4X) invalid device name(%s)"
#define HHCCT062E "Device(%4.4X) Invalid MTU size(%s)"
#define HHCCT072W "Device(%4.4X) Packet too big; dropped"
#define HHCCT073I "Device(%4.4X) TUN device(%s) opened"
#define HHCCT074W "TT32SDEVBUFF failed for device(%s): %s"
#define HHCCT075W "TT32SIOBUFF failed for device(%s): %s"

/* ctc_lcs.c */
#define HHCLC001E "Device(%4.4X) Unable to allocate LCSBLK"
#define HHCLC002I "Device(%4.4X) Halt or Clear Recognized"
#define HHCLC003I "Device(%4.4X) LCS Read"
#define HHCLC004I "Device(%4.4X) Sending packet to file(%s)"
#define HHCLC006I "Device(%4.4X) Triggering Event"
#define HHCLC007E "Error in call to socket: %s"
#define HHCLC008E "ioctl error on device(%s) %s"
#define HHCLC009I "Port(%2.2X) Read Buffer:"
#define HHCLC010I "Port(%2.2X) IPV4 frame for %8.8X"
#define HHCLC011I "Port(%2.2X) ARP frame for %8.8X"
#define HHCLC012I "Port(%2.2X) SNA frame"
#define HHCLC013I "Port(%2.2X) No match found - selecting primary %4.4X"
#define HHCLC014I "Port(%2.2X) No match found - selecting secondary %4.4X"
#define HHCLC015I "Port(%2.2X) No match found - Discarding frame"
#define HHCLC016I "Port(%2.2X) Enqueing frame to device %4.4X (%8.8X)"
#define HHCLC017E "Device(%4.4X) invalid device name(%s)"
#define HHCLC018E "Device(%4.4X) invalid MAC address(%s)"
#define HHCLC019E "Device(%4.4X) too many arguments in statement"
#define HHCLC020E "Device(%4.4X) invalid IP address(%s)"
#define HHCLC021E "Invalid HWADD statement in %s: %s"
#define HHCLC022E "Invalid MAC in HWADD statement in %s: %s (%s)"
#define HHCLC023E "Invalid ROUTE statement in %s: %s"
#define HHCLC024E "Invalid net address in ROUTE %s: %s (%s)"
#define HHCLC025E "Invalid net mask in ROUTE %s: %s (%s)"
#define HHCLC026E "Error in %s: Missing device number or mode"
#define HHCLC027E "Error in %s: %s: Invalid device number"
#define HHCLC028E "Error in %s: %s:Missing PORT number"
#define HHCLC029E "Error in %s: %s: Invalid PORT number"
#define HHCLC031E "Error in %s: %s: Invalid entry starting at %s"
#define HHCLC032E "Error in %s: %s: Invalid IP address (%s)"
#define HHCLC033E "Error in %s: %s: Missing PORT number"
#define HHCLC034E "Error in %s: %s: Invalid PORT number"
#define HHCLC035E "Error in %s: %s: SNA does not accept any arguments"
#define HHCLC036E "Error in %s: %s: Invalid MODE"
#define HHCLC037E "Error reading file(%s) line(%d): %s"
#define HHCLC038E "File(%s) line(%d) is too long"
#define HHCLC039E "Cannot open file(%s): %s"
#define HHCLC040E "Device(%4.4X) LCSDEV(%4.4X) not in configuration"
#define HHCLC041W "Port(%2.2X) Frame too big; discarded"
#define HHCLC042E "Port(%2.2X) Read error: %s"
#define HHCLC043I "Device(%4.4X) Startup"
#define HHCLC044I "Device(%4.4X) Shutdown"
#define HHCLC045I "Device(%4.4X) Start LAN"
#define HHCLC046I "Device(%4.4X) Stop LAN"
#define HHCLC047I "Device(%4.4X) Query IP Assists"
#define HHCLC048I "Device9%4.4X) Statistics"
#define HHCLC049W "Device(%4.4X) LCS_Startup: Requested frame buffer size of 0x%4.4X larger than compiled size of 0x%4.4X; requested size ignored"
#define HHCLC050E "Device(%4.4X) LCS_Write: Unsupported frame type(0x%2.2X)"
#define HHCLC051I "Device(%4.4X) Cmd Packet"
#define HHCLC052E "Device(%4.4X) Invalid kernel buffer size(%s)"
#define HHCLC053E "Device(%4.4X) Invalid DLL I/O buffer size(%s)"
#define HHCLC054W "Device(%4.4X) LCS_Startup: Requested frame buffer size of 0x%4.4X smaller than compiled minimum size of 0x%4.4X; requested size ignored"
#define HHCLC055I "%s using MAC %2.2X:%2.2X:%2.2X:%2.2X:%2.2X:%2.2X"
#define HHCLC056W "%s NOT using MAC %2.2X:%2.2X:%2.2X:%2.2X:%2.2X:%2.2X"
#define HHCLC073I "Device(%4.4X) TAP device(%s) opened"
#define HHCLC074W "TT32SDEVBUFF failed for device(%s) %s"
#define HHCLC075W "TT32SIOBUFF failed for device(%s) %s"
#define HHCLC076I "Port(%2.2X) RARP frame for %2.2X:%2.2X:%2.2X:%2.2X:%2.2X:%2.2X"

/* ctcadpt.c */
#define HHCCT001E "Device(%4.4X) Incorrect number of parameters"
#define HHCCT002E "Device(%4.4X) Incorrect number of parameters"
#define HHCCT003E "Device(%4.4X) Invalid port number(%s)"
#define HHCCT004E "Device(%4.4X) Invalid IP address(%s)"
#define HHCCT005E "Device(%4.4X) Invalid port number(%s)"
#define HHCCT006E "Device(%4.4X) Invalid MTU size(%s)"
#define HHCCT007E "Device(%4.4X) Error creating socket(%s)"
#define HHCCT008E "Device(%4.4X) Error binding socket(%s)"
#define HHCCT009I "Device(%4.4X) Connect to %s:%s failed, starting server"
#define HHCCT010E "Device(%4.4X) Error creating socket: %s"
#define HHCCT011E "Device(%4.4X) Error binding socket(%s)"
#define HHCCT012E "Device(%4.4X) Error on call to listen: %s"
#define HHCCT013I "Device(%4.4X) Connected to %s:%s"
#define HHCCT014E "Device(%4.4X) Write CCW count %u is invalid"
#define HHCCT015I "Device(%4.4X) Interface command: %s %8.8X"
#define HHCCT016E "Device(%4.4X) Write buffer contains incomplete segment header at offset %4.4X"
#define HHCCT017E "Device(%4.4X) Write buffer contains invalid segment length %u at offset %4.4X"
#define HHCCT018I "Device(%4.4X) Sending packet to file(%s)"
#define HHCCT019E "Device(%4.4X) Error writing to file(%s): %s"
#define HHCCT020E "Device(%4.4X) Error reading from file(%s): %s"
#define HHCCT021E "Device(%4.4X) Error reading from file(%s): %s"
#define HHCCT022I "Device(%4.4X) Received packet from %s (%d bytes)"
#define HHCCT023E "Device(%4.4X) Incorrect client or config error: Config(%s) connecting client(%s)"
#define HHCCT024E "Device(%4.4X) Not enough arguments to start vmnet"
#define HHCCT025E "Device(%4.4X) Failed: socketpair: %s"
#define HHCCT026E "Device(%4.4X) Failed: fork: %s"
#define HHCCT027E "Device(%4.4X) Not enough parameters"
#define HHCCT028E "Device(%d:%4.4X): Bad device number(%s)"
#define HHCCT029E "Device(%4.4X) bad block length: %d < %d"
#define HHCCT030E "Device(%4.4X) bad packet length: %d < %d"
#define HHCCT032E "Device(%4.4X) Error: EOF on read, CTC network down"
#define HHCCT033E "Device(%4.4X) Error: read: %s"
#define HHCCT034E "Unrecognized/unsupported CTC emulation type(%s)"

/* diagnose.c */
#define HHCDN001I "Diagnose 0x308 called: System is re-ipled"
#define HHCDN002I "Checking cpu(%d)"
#define HHCDN003I "Waiting 1 second for cpu's to stop"
#define HHCDN004E "Error starting thread in diagnose 0x308: %s"

/* dynguic. */
#define HHCDG001I "Dyngui.dll initiated"
#define HHCDG002I "Dyngui.dll terminated"
#define HHCDG003S "Select failed on input stream: %s"
#define HHCDG004S "Read failed on input stream: %s"
#define HHCDG005E "Device(%4.4X) query buffer overflow"

/* ecpsvm.c */
#define HHCEV001I "| %-9s | %8d | %8d |  %3d%% |"
#define HHCEV002I "| %-9s | %-8s | %-8s | %-5s |"
#define HHCEV003I "+-----------+----------+----------+-------+"
#define HHCEV004W "Abend condition detected in DISP2 instr"
#define HHCEV005I "%d Entr%s not shown (never invoked)"
#define HHCEV006I "%d call(s) was/where made to unsupported functions"
#define HHCEV008E "NO EVM subcommand. Type \"evm help\" for a list of valid subcommands"
#define HHCEV010I "%s : %s"
#define HHCEV011E "Unknown subcommand %s - valid subcommands are :"
#define HHCEV012I "%s : %s"
#define HHCEV013I "ECPS:VM Global Debug %s"
#define HHCEV014I "ECPS:VM %s feature %s %s%s"
#define HHCEV015I "ECPS:VM %s feature %s%s%s"
#define HHCEV016I "All ECPS:VM %s features %s%s"
#define HHCEV017I "But ECPS:VM is currently disabled"
#define HHCEV018W "WARNING ! Unpredictable results may occur"
#define HHCEV019I "The microcode support level is 20"
#define HHCEV024I "* : Unsupported, - : Disabled, %% - Debug"
#define HHCEV025I "Unknown ECPS:VM feature %s; Ignored"
#define HHCEV026I "Current reported ECPS:VM Level is %d"
#define HHCEV027I "Level reported to guest program is now %d"
#define HHCEV028W "WARNING ! current level (%d) is not supported"
#define HHCEV029I "ECPS:VM Command processor invoked"
#define HHCEV030E "Unknown EVM subcommand %s"
#define HHCEV031I "ECPS:VM Command processor complete"

/* external.c */
#define HHCCP023I "External interrupt: Interrupt key"
#define HHCCP024I "External interrupt: Clock comparator"
#define HHCCP025I "External interrupt: CPU timer=%16.16" I64_FMT "X"
#define HHCCP026I "External interrupt: Interval timer"
#define HHCCP027I "External interrupt: Service signal %8.8X"
#define HHCCP028I "External interrupt: Block I/O %s"
#define HHCCP031I "Device(%4.4X) Processing Block I/O interrupt: code(%4.4X) parm(%16.16X) status(%2.2X) subcode(%2.2X)"

/* faketape.c */
#define HHCTA501I "Device(%4.4X) FakeTape(%s) closed"
#define HHCTA502E "Device(%4.4X) Error opening file(%s) %s"
#define HHCTA503E "Device(%4.4X) Error seeking to offset("I64_FMTX")in file(%s) %s"
#define HHCTA504E "Device(%4.4X) Error reading block header at offset("I64_FMTX") in file(%s) %s"
#define HHCTA505E "Device(%4.4X) End of file (end of tape) at offset("I64_FMTX") in file(%s)"
#define HHCTA506E "Device(%4.4X) Unexpected end of file in block header at offset("I64_FMTX") in file(%s)"
#define HHCTA507E "Device(%4.4X) Block header damage at offset("I64_FMTX") in file(%s)"
#define HHCTA510E "Device(%4.4X) Error reading data block at offset("I64_FMTX") in file(%s) %s"
#define HHCTA511E "Device(%4.4X) Unexpected end of file in data block at offset("I64_FMTX") in file(%s)"
#define HHCTA512E "Device(%4.4X) Error seeking to offset("I64_FMTX") in file(%s) %s"
#define HHCTA513E "Device(%4.4X) Media full condition reached at offset("I64_FMTX") in file(%s)"
#define HHCTA514E "Device(%4.4X) Error writing block header at offset("I64_FMTX") in file(%s) %s"
#define HHCTA515E "Device(%4.4X) Error seeking to offset("I64_FMTX") in file(%s) %s"
#define HHCTA517E "Device(%4.4X) Error writing data block at offset("I64_FMTX") in file(%s) %s"
#define HHCTA520E "Device(%4.4X) Error writing tape mark at offset("I64_FMTX") in file(%s) %s"
#define HHCTA521E "Device(%4.4X) Sync error on file(%s) %s"

/* fbadasd.c */
#define HHCDA056E "File name missing or invalid"
#define HHCDA057E "Device(%4.4X) File not found or invalid"
#define HHCDA058E "File(%s) open error %s"
#define HHCDA059E "Read error in file(%s) %s"
#define HHCDA060E "Unexpected end of file(%s)"
#define HHCDA063E "Parameter(%d) is invalid %s"
#define HHCDA064E "File(%s) fstat error %s"
#define HHCDA065E "Invalid device origin block number(%s)"
#define HHCDA066E "Invalid device block count(%s)"
#define HHCDA067I "File(%s) origin(%lld) blks(%d)"
#define HHCDA068E "Device(%4.4X) device type(%4.4X) not found in dasd table"
#define HHCDA069E "Error writing blkgrp(%d) lseek error(%s)"
#define HHCDA070E "Error writing blkgrp(%d) write error(%s)"
#define HHCDA071I "Read blkgrp(%d) cache hit, using cache[%d]"
#define HHCDA072I "Read blkgrp(%d) no available cache entry, waiting"
#define HHCDA073I "Read blkgrp(%d) cache miss, using cache[%d]"
#define HHCDA074I "Read blkgrp(%d) offset(%" I64_FMT "d) len(%d)"
#define HHCDA075E "Error reading blkgrp(%d) lseek error(%s)"
#define HHCDA076E "Error reading blkgrp(%d) read error(%s)"
#define HHCDA077I "Positioning to %8.8" I64_FMT "X (%" I64_FMT "u)"
#define HHCDA078E "Define extent data too short: %d bytes"
#define HHCDA079E "Second define extent in chain"
#define HHCDA080E "Invalid file mask(%2.2X)"
#define HHCDA081E "Invalid extent: first block(%d) last block(%d) numblks(%d) device size(%d)"
#define HHCDA082E "File(%s) IOCTL BLKGETSIZE error %s"
#define HHCDA901E "Device(%4.4X) FBA origin mismatch: %d, expected %d,"
#define HHCDA902E "Device(%4.4X) FBA numblk mismatch: %d, expected %d,"
#define HHCDA903E "Device(%4.4X) FBA blksiz mismatch: %d, expected %d,"

/* hao.c */
#define HHCAO001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCAO002I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCAO003I "Firing command: (%s)"
#define HHCAO004I "The defined Automatic Operator rule(s) are:"
#define HHCAO005I "(%02d): (%s) -> (%s)"
#define HHCAO006I "(%d) rule(s) displayed"
#define HHCAO007E "Unknown hao command, valid commands are:\n" \
                  "          hao tgt <tgt> : define target rule (pattern) to react on\n" \
                  "          hao cmd <cmd> : define command for previously defined rule\n" \
                  "          hao list <n>  : list all rules/commands or only at index <n>\n" \
                  "          hao del <n>   : delete the rule at index <n>\n" \
                  "          hao clear     : delete all rules (stops automatic operator)"
#define HHCAO008E "No rule defined at index(%d)"
#define HHCAO009E "Invalid index, index must be between 0 and (%d)"
#define HHCAO010E "Target not added, table full"
#define HHCAO011E "Tgt command given, but cmd command expected"
#define HHCAO012E "Empty target specified"
#define HHCAO013E "Target not added, duplicate found in table"
#define HHCAO014E "%s"
#define HHCAO015E "%s"
#define HHCAO016I "Target placed at index(%d)"
#define HHCAO017E "Cmd command given, but tgt command expected"
#define HHCAO018E "Empty command specified"
#define HHCAO019E "Command not added; causes loop with target at index(%d)"
#define HHCAO020I "Command placed at index(%d)"
#define HHCAO021E "Target not added, causes loop with command at index(%d)"
#define HHCAO022I "All automatic operation rules cleared"
#define HHCAO023E "Hao del command given without a valid index"
#define HHCAO024E "Rule at index(%d) not deleted, already empty"
#define HHCAO025I "Rule at index(%d) succesfully deleted"
#define HHCA0026E "Command not added, may cause dead locks"

/* hchan.c */
#define HHCGCH001E "Device(%4.4X) Incorrect Generic Channel method(%s)"
#define HHCGCH002T "Device(%4.4X) Generic channel initialisation failed"
#define HHCGCH003E "Device(%4.4X) Missing Generic Channel method"
#define HHCGCH999W "Device(%4.4X) Generic channel is currently in development"

/* hdl.c */
#define HHCHD001E "Registration malloc failed for (%s)"
#define HHCHD005E "Module(%s) already loaded\n"
#define HHCHD006S "Cannot allocate memory for DLL descriptor: (%s)"
#define HHCHD007E "Unable to open DLL(%s): (%s)"
#define HHCHD008E "Device(%4.4X) bound to (%s)"
#define HHCHD009E "Module(%s) not found"
#define HHCHD010I "Dependency check failed for (%s), version(%s) expected(%s)"
#define HHCHD011I "Dependency check failed for (%s), size(%d) expected(%d)"
#define HHCHD013E "No dependency section in (%s): (%s)"
#define HHCHD014E "Dependency check failed for module(%s)"
#define HHCHD015E "Unloading of module(%s) not allowed"
#define HHCHD016E "DLL(%s) is duplicate of (%s)"
#define HHCHD017E "Unload of module(%s) rejected by final section"
#define HHCHD018I "Loadable module directory is (%s)"
#define HHCHD900I "Begin shutdown sequence"
#define HHCHD901I "Calling (%s)"
#define HHCHD902I "(%s) complete"
#define HHCHD903I "(%s) skipped during Windows SHUTDOWN immediate"
#define HHCHD909I "Shutdown sequence complete"
#define HHCHD950I "Begin HDL termination sequence"
#define HHCHD951I "Calling module(%s) cleanup routine"
#define HHCHD952I "Module(%s) cleanup complete"
#define HHCHD959I "HDL Termination sequence complete"

/* hettape.c */
#define HHCTA401E "Device(%4.4X) Error opening file(%s) %s(%s)"
#define HHCTA402E "Device(%4.4X) Error seeking to start of file(%s) %s(%s)"
#define HHCTA414E "Device(%4.4X) End of file (end of tape) at block(%8.8X) in file(%s)"
#define HHCTA415E "Device(%4.4X) Error reading data block at block(%8.8X) in file(%s) %s(%s)"
#define HHCTA416E "Device(%4.4X) Error writing data block at block(%8.8X) in file(%s) %s(%s)"
#define HHCTA417E "Device(%4.4X) Error writing tape mark at block(%8.8X) in file(%s) %s(%s)"
#define HHCTA418E "Device(%4.4X) Error forward spacing at block(%8.8X) in file(%s) %s(%s)"
#define HHCTA420E "Device(%4.4X) Error forward spacing to next file at block(%8.8X) in file(%s) %s(%s)"
#define HHCTA421E "Device(%4.4X) Error back spacing to previous file at block(%8.8X) in file(%s) %s(%s)"
#define HHCTA430I "Device(%4.4X) max tape capacity exceeded"
#define HHCTA431I "Device(%4.4X) max tape capacity enforced"
#define HHCTA488E "Device(%4.4X) Sync error on file(%s) %s"

/* hostinfo.c */
#define HHCIN015I "%s"

/* httpserv.c */
#define HHCHT001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCHT002E "Socket error: (%s)"
#define HHCHT003W "Waiting for port(%u) to become free"
#define HHCHT004E "Bind error: (%s)"
#define HHCHT005E "Listen error: (%s)"
#define HHCHT006I "Waiting for HTTP requests on port(%u)"
#define HHCHT007E "Select error: (%s)"
#define HHCHT008E "Accept error: (%s)"
#define HHCHT009I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCHT010E "Http_request create_thread error: (%s)"
#define HHCHT011E "Html_include: Cannot open file(%s): (%s)"
#define HHCHT013I "Using HTTPROOT directory (%s)"
#define HHCCF066E "Invalid HTTPROOT: (%s): (%s)"

/* impl.c */
#define HHCIN001S "Cannot register SIGINT handler: %s"
#define HHCIN002E "Cannot suppress SIGPIPE signal: %s"
#define HHCIN003S "Cannot register SIGILL/FPE/SEGV/BUS/USR handler: %s"
#define HHCIN004S "Cannot create HAO thread: %s"
#define HHCIN005S "Cannot create watchdog thread: %s"
#define HHCIN006S "Cannot create shared_server thread: %s"
#define HHCIN007S "Cannot create %4.4X connection thread: %s"
#define HHCIN008S "DYNGUI.DLL load failed; Hercules terminated."
#define HHCIN009S "Cannot register SIGTERM handler: %s"
#define HHCIN010S "Cannot register ConsoleCtrl handler: %s"
#define HHCIN021I "CLOSE Event received, SHUTDOWN Immediate starting..."
#define HHCIN022I "Ctrl-C intercepted"
#define HHCIN023W "CLOSE Event received, SHUTDOWN previously requested..."
#define HHCIN050I "Ctrl-Break intercepted. Interrupt Key depressed simulated."
#define HHCIN099I "Hercules terminated"
#define HHCIN950I "Begin system cleanup"
#define HHCIN959I "System cleanup complete"
#define HHCPN995E ".RC file \"%s\" not found."

/* ipl.c */
#define HHCCP027E "Device(%4.4X) not in configuration%s"
#define HHCCP029E "Arch mode(%s) IPL failed: CSW status(%2.2X%2.2X) Sense(%s)"
#define HHCCP030E "Arch mode(%s) IPL failed: Invalid IPL PSW(%2.2X%2.2X%2.2X%2.2X %2.2X%2.2X%2.2X%2.2X)"

/* logger.c */
#define HHCLG014E "Log not active"
#define HHCLG015I "Log closed"
#define HHCLG016E "Error opening logfile(%s) %s"
#define HHCLG017S "Log file(%s) fdopen failed %s"

/* machchk.c */
#define HHCCP017I "Processor(%s%02X) Machine check due to host error(%s)"
#define HHCCP018I "Processor(%s%02X) Check-Stop due to host error: %s"
#define HHCCP019I "Machine Check code(%16.16" I64_FMT "u)"
#define HHCCP020E "Signal USR2 received for undetermined device"
#define HHCCP021E "Signal USR2 received for device(%4.4X)"

/* omatape.c */
#define HHCTA239E "Device(%4.4X) Error opening TDF file(%s) %s"
#define HHCTA240E "Device(%4.4X) File(%s) fstat error %s"
#define HHCTA241E "Device(%4.4X) Cannot obtain buffer for TDF file(%s) %s"
#define HHCTA242E "Device(%4.4X) Error reading TDF file(%s) %s"
#define HHCTA243E "Device(%4.4X) file(%s) is not a valid TDF file"
#define HHCTA244E "Device(%4.4X) Cannot obtain buffer for TDF array %s"
#define HHCTA245E "Device(%4.4X) Filename or format missing in line(%d) of file(%s)"
#define HHCTA246E "Device(%4.4X) Filename(%s) too long in line(%d) of file(%s)"
#define HHCTA247E "Device(%4.4X) RECSIZE keyword missing in line(%d) of file(%s)"
#define HHCTA248E "Device(%4.4X) Invalid record size(%s) in line(%d) of file(%s)"
#define HHCTA249E "Device(%4.4X) Invalid record format(%s) in line(%d) of file(%s)"
#define HHCTA251E "Device(%4.4X) Error opening file(%s) %s"
#define HHCTA252E "Device(%4.4X) Error seeking to offset("I32_FMTX") in file(%s) %s"
#define HHCTA253E "Device(%4.4X) Error reading block header at offset("I32_FMTX") in file(%s) %s"
#define HHCTA254E "Device(%4.4X) Unexpected end of file in block header at offset("I32_FMTX") in file(%s)"
#define HHCTA255E "Device(%4.4X) Invalid block header at offset("I32_FMTX") in file(%s)"
#define HHCTA256E "Device(%4.4X) Error reading data block at offset("I32_FMTX") in file(%s) %s"
#define HHCTA257E "Device(%4.4X) Unexpected end of file in data block at offset("I32_FMTX") in file(%s)"
#define HHCTA263E "Device(%4.4X) Invalid zero length block at offset("I32_FMTX") in file(%s)"
#define HHCTA264E "Device(%4.4X) Error seeking to end of file(%s) %s"

/* panel.c */
#define HHCPN001I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCPN002S "Cannot obtain keyboard buffer: (%s)"
#define HHCPN003S "Cannot obtain message buffer: (%s)"

/* printer.c */
#define HHCPR001E "Device(%4.4X) file name missing or invalid for printer"
#define HHCPR002E "Printer(%4.4X) Invalid argument(%s)"
#define HHCPR003E "Device(%4.4X) Error writing to file(%s) %s"
#define HHCPR004E "Error opening file(%s) %s"
#define HHCPR005E "Device(%4.4X) initialization error: pipe %s"
#define HHCPR006E "Device(%4.4X) initialization error: fork %s"
#define HHCPR007I "Device(%4.4X) Pipe receiver pid(%d) starting"
#define HHCPR008E "Device(%4.4X) dup2 error: %s"
#define HHCPR009E "Parameter(%s) #(%d) is invalid"
#define HHCPR010E "Parameter(%s) #(%d) pos(%d) is invalid"
#define HHCPR011I "Device(%4.4X) pipe receiver pid(%d) terminating"
#define HHCPR012E "Device(%4.4X) Unable to execute file(%s) %s"
#define HHCPR015E "Device(%4.4X) create spthread failed errno(%d) %s"
#define HHCPR016I "%s (%s) disconnected from device %4.4X (%s)"
#define HHCPR019E "Printer(%4.4X) Incompatible option(%s) specified"

/* pttrace.c */
#define HHCPT001E "Invalid argument(%s)"
#define HHCPT002E "Trace is busy"
#define HHCPT003I "Ptt(%s%s%s%s%s%s%s%s%s%s%s %s %s) to(%d %d)"

/* scedasd.c */
#define HHCSC001E "Load from file(%s) failed: %s"
#define HHCSC003E "Load from path(%s) failed: %s"
#define HHCSC011E "set_sce_dir: %s: %s"
#define HHCSC012E "set_sce_basedir: %s: %s"
#define HHCSC031E "load_main: %s: %s"
#define HHCSC032W "load_main: terminated at end of mainstor"
#define HHCSC041E "File(%s) open error: %s"
#define HHCSC101E "access error: %s: %s"
#define HHCSC201E "File(%S) access error: %s"

/* scsitape.c */
#define HHCTA300I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTA301I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTA323I "%s"
#define HHCTA324E "Error opening %u:%4.4X=%s; errno=%d: %s"
#define HHCTA330E "Error setting attributes for %u:%4.4X=%s; errno=%d: %s"
#define HHCTA332E "Error reading data block from %u:%4.4X=%s; errno=%d: %s"
#define HHCTA333E "Error writing data block to %u:%4.4X=%s; errno=%d: %s"
#define HHCTA334E "Error writing tapemark to %u:%4.4X=%s; errno=%d: %s"
#define HHCTA335E "Forward space block error on %u:%4.4X=%s; errno=%d: %s"
#define HHCTA336E "Backspace block error on %u:%4.4X=%s; errno=%d: %s"
#define HHCTA337E "Forward space file error on %u:%4.4X=%s; errno=%d: %s"
#define HHCTA338E "Backspace file error on %u:%4.4X=%s; errno=%d: %s"
#define HHCTA373E "Error rewinding %u:%4.4X=%s; errno=%d: %s"
#define HHCTA376E "Error unloading %u:%4.4X=%s; errno=%d: %s"
#define HHCTA377I "Tape %u:%4.4X unloaded"
#define HHCTA380E "Erase gap error on %u:%4.4X=%s; errno=%d: %s"
#define HHCTA381E "Data Security Erase error on %u:%4.4X=%s; errno=%d: %s"
#define HHCTA382W "ioctl_tape(MTIOCPOS=MTTELL) failed on %4.4X = %s: %s"
#define HHCTA383W "ioctl_tape(MTIOCTOP=MTSEEK) failed on %4.4X = %s: %s"
#define HHCTA389E "Synchronize error on %u:%4.4X=%s; errno=%d: %s"

/* service.c */
#define HHCCP012I "Processor(%s%02X) Vector Facility configured offline"
#define HHCCP013I "Processor(%s%02X) Vector Facility configured online"
#define HHCCP036E "SCP not receiving priority messages"
#define HHCCP037E "SCP not receiving commands"
#define HHCCP038E "No SCP command"
#define HHCCP081E "SCP not receiving quiesce signals"
#define HHCCP040I "Control program information type(%s) name(%s) sysplex(%s) level(%16.16"I64_FMT"X)"
#define HHCCP041I "SYSCONS interface active"
#define HHCCP042I "SYSCONS interface inactive"
#define HHCCP090W "The configuration has been placed into a system check-stop state because of an incompatible service call"

/* shared.c */
#define HHCSH001S "Parameter #(%d) is invalid: %s"
#define HHCSH002W "Device(%4.4X) connect pending to file(%s)"
#define HHCSH003S "Device(%4.4X) Error retrieving cylinders"
#define HHCSH004S "Device(%4.4X) Error retrieving device characteristics"
#define HHCSH005S "Device(%4.4X) Remote device(%4.4X) is a %4.4X"
#define HHCSH006S "Device(%4.4X) Error retrieving device id"
#define HHCSH007S "Device(%4.4X) device type %4.4X not found in dasd table"
#define HHCSH008S "Device(%4.4X) control unit(%s) not found in dasd table"
#define HHCSH009I "File(%s) cyls(%d) heads(%d) tracks(%d) trklen(%d)"
#define HHCSH012S "Device(%4.4X) Error retrieving fba origin"
#define HHCSH013S "Device(%4.4X) Error retrieving fba number blocks"
#define HHCSH014S "Device(%4.4X) Error retrieving fba block size"
#define HHCSH019I "File(%s) origin(%d) blks(%d)"
#define HHCSH020E "Device(%4.4X) error during channel program start"
#define HHCSH021E "Device(%4.4X) error during channel program end"
#define HHCSH022E "Device(%4.4X) error reading track(%d)"
#define HHCSH024E "Device(%4.4X) error reading block group(%d)"
#define HHCSH026E "Device(%4.4X) Error retrieving usage information"
#define HHCSH027E "Device(%4.4X) error writing track(%d)"
#define HHCSH028E "Device(%4.4X) remote error writing track(%d) %2.2X-%2.2X"
#define HHCSH029E "Device(%4.4X) socket failed: %s"
#define HHCSH031I "Device(%4.4X) Connected to file(%s)"
#define HHCSH032E "Device(%4.4X) Connect to file(%s) errno(%d): %s"
#define HHCSH033E "Device(%4.4X) send error(%d) for %2.2X-%2.2X: %s"
#define HHCSH034E "Device(%4.4X) Not connected to file(%s)"
#define HHCSH035E "Device(%4.4X) recv error(%d): %s"
#define HHCSH036E "Device(%4.4X) Remote error %2.2X-%2.2X: %s"
#define HHCSH037E "Decompress error(%d) off(%d) len(%d)"
#define HHCSH038E "Data compressed using libz, unsupported"
#define HHCSH040E "Data compressed using bzip2, unsupported"
#define HHCSH041E "Device(%4.4X) send error(%d) id(%d) %s"
#define HHCSH042W "Device(%4.4X) busy client being removed id(%d) %s"
#define HHCSH043I "%s disconnected from device(%4.4X) id(%d)"
#define HHCSH0474 "Connect to ip(%s) failed"
#define HHCSH053I "Ip(%s) connected to device(%4.4X) id(%d)"
#define HHCSH045I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSH046E "Select error: %s"
#define HHCSH047E "Device(%4.4X) ip(%s) recv error id(%d)"
#define HHCSH048I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSH050E "inet socket: %s"
#define HHCSH051W "unix socket: %s"
#define HHCSH052W "Waiting for port(%u) to become free"
#define HHCSH053E "inet bind: %s"
#define HHCSH054W "unix bind: %s"
#define HHCSH055E "inet listen: %s"
#define HHCSH056W "unix listen: %s"
#define HHCSH057I "Waiting for shared device requests on port(%u)"
#define HHCSH058E "select: %s"
#define HHCSH059E "accept: %s"
#define HHCSH060E "malloc size %d: %s"
#define HHCSH061E "serverConnect create_thread: %s"
#define HHCSH062E "Invalid or missing argument 1"
#define HHCSH063E "Invalid or missing keyword 2"
#define HHCSH064E "Invalid or missing value %s"
#define HHCSH065E "calloc() size=%d: %s"
#define HHCSH066E "Invalid or missing keyword(%s)"
#define HHCSH999E "OPTION_SHARED_DEVICES not defined"

/* sie.c */ /* BHe should we calloc the sieregs? Why not statical?? */
#define HHCCP079E "Processor(%s%02X) calloc failed for sie regs: %s"

/* sockdev.c */
#define HHCSD001E "Device(%4.4X) already bound to socket(%s)"
#define HHCSD002E "Device(%4.4X) bind_device malloc() failed"
#define HHCSD003E "Device(%4.4X) bind_device strdup() failed"
#define HHCSD004I "Device(%4.4X) bound to socket(%s)"
#define HHCSD005E "Device(%4.4X) not bound to any socket"
#define HHCSD006E "Client(%s) ip(%s) still connected to device(%4.4X) (%s)"
#define HHCSD007I "Device(%4.4X) unbound from socket(%s)"
#define HHCSD008E "Socket pathname(%s) exceeds limit(%d)"
#define HHCSD009E "Error creating socket(%s) %s"
#define HHCSD010E "Failed to bind or listen on socket(%s) %s"
#define HHCSD011E "Failed to determine IP address from node(%s)"
#define HHCSD012E "Failed to determine port number from service(%s)"
#define HHCSD015E "Client(%s) ip(%s) connection to device(%4.4X) (%s) rejected: device busy or interrupt pending"
#define HHCSD016E "Client(%s) ip(%s) connection to device(%4.4X) (%s) rejected: client(%s) ip(%s) still connected"
#define HHCSD017E "Connect to device(%4.4X) (%s) failed: %s"
#define HHCSD018I "Client(%s) ip(%s) connected to device(%4.4X) (%s)"
#define HHCSD020I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSD021E "select failed; errno(%d) %s"
#define HHCSD022I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCSD023E "Cannot create socketdevice thread: errno(%d) %s"
#define HHCSD024E "This build does not support Unix domain sockets"
#define HHCSD025I "Client(%s) ip(%s) disconnected from device(%4.4X) (%s)"
#define HHCSD026E "Client(%s) ip(%s) connection to device(%4.4X) (%s) rejected: by onconnect callback"

/* sr.c */
#define HHCSR001I "Resuming suspended file(%s) created"
#define HHCSR010E "Write error(%s)"
#define HHCSR011E "Read error(%s)"
#define HHCSR013E "Value error, incorrect length"
#define HHCSR014E "String error, incorrect length"
#define HHCSR015E "Error processing file(%s)"
#define HHCSR016E "CPU key(%8.8X) found but no active CPU"
#define HHCSR101E "Too many arguments"
#define HHCSR102E "File(%s) open error(%s)"
#define HHCSR103W "Waiting for device(%4.4X)"
#define HHCSR104W "Device(%4.4X) still busy, proceeding anyway"
#define HHCSR105E "Archmode(%s) not supported"
#define HHCSR106E "Mainsize mismatch: %dM expected %dM"
#define HHCSR108E "Storkey size mismatch: %d expected %d"
#define HHCSR110E "Xpndsize mismatch: %dM expected %dM"
#define HHCSR113E "Processor(%s%02X) exceeds max allowed cpu(%02d)"
#define HHCSR114E "Processor(%s%02X) already configured"
#define HHCSR115E "Processor(%s%02X) unable to configure online"
#define HHCSR116E "Processor(%s%02X) invalid psw length(%d)"
#define HHCSR117E "Processor(%s%02X) error loading psw - rc(%d)"
#define HHCSR118W "Device(%4.4X) initialization failed"
#define HHCSR119W "Device(%4.4X) type mismatch; %s expected %s"
#define HHCSR120E "Device(%4.4X) %s size mismatch: %d expected %d"
#define HHCSR132E "Device(%4.4X) type mismatch: %4.4X expected %4.4X"
#define HHCSR133E "Device(%4.4X) Unable to resume suspended device: %s"
#define HHCSR203E "All CPU's must be stopped to resume"
#define HHCSR204E "File identifier error"
#define HHCSR999E "Invalid key %8.8x"

/* timer.c */
#define HHCTT001W "Timer thread set priority(%d) failed: (%s)"
#define HHCTT002I "Thread started tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"
#define HHCTT003I "Thread ended tid(" TIDPAT ") pid(%d) prio(%d) name(%s)"

/* version.c */
#define HHCIN010I "%sversion (%s)"
#define HHCIN011I "%s"
#define HHCIN012I "Built on (%s) at (%s)"
#define HHCIN013I "Build information:"
#define HHCIN014I "%s"
