#!/bin/bash

# Note: UNIX and REXX required.

# This  file  was  put  into  the  public  domain 2015-10-05 by John P.
# Hartmann.   You  can  use  it  for anything you like, as long as this
# notice remains.

# Anything  said  in  comments in this file assumes that you have built
# Hercules by git pull; autogen.sh; make.

# This script is in support of "make check".  If run by hand, it should
# be  invoked  from  the  top level object directory, "hyperion" if you
# configured  in  the source tree; the external object directory if you
# configured elsewhere.

# Arguments:

# 1     Path  from the current directory to the tests source directory.
#       Specify - (minus, hyphen) for the default ../hyperion/tests

# 2     File  name  of  test  case  omitting  the .tst extension or the
#       default  '*'  for  all .tst files.  Quote the asterisk to avoid
#       premature file name expansion.  But see #4.

# 3     Specify  noexit  to  suppress  the  exit  command that normally
#       terminates  the test cases.  This will allow you to poke around
#       with  console commands after the test script has run.  Anything
#       else,  including nothing adds an exit command at the end of the
#       composite script.

# 4     File type of test cases.  Default .tst.

# To run a specific test case:
#       ../hyperion/tests/runtest - <fname>
# Again, be sure to omit the extension.

# Tests  are  normally  done alphabetically.  You can use the scripting
# facilities  to  include specific test case files in any order, but do
# not  give these embedded files the default extension (unless you want
# them run twice!).

wfn=allTests

dir=${1:-../hyperion/tests}
if [ "$dir" == "-" ] ; then
        dir=../hyperion/tests
fi

fns=${2:-*}
ftype=${4:-tst}

# Generate composite file of all test cases.  File name expansion sorts
# it   alphabetically   (some   shell   variants   ignore  case  and/or
# punctuation).

cat $dir/$fns.$ftype >$wfn.tst

# Run the script through Hercules.  2>&1 disables the panel display and
# the ability to enter panel commands.

if [ "$3" != "noexit" ] ; then
        echo exit >>$wfn.tst
        ./hercules -f $dir/tests.conf -r $wfn.tst >$wfn.out 2>&1
else
        ./hercules -f $dir/tests.conf -r $wfn.tst >$wfn.out
fi

# Read entire file to allow redtest.rexx to parse the features list
rexx $dir/redtest.rexx $wfn.out
