#!/bin/bash

# Note: UNIX and REXX required.

# This  file  was  put  into  the  public  domain 2015-10-05 by John P.
# Hartmann.   You  can  use  it  for anything you like, as long as this
# notice remains.

# This script should be invoked from the top level object directory,
# hyperion if you configured in the source tree; the external object
# directory if you configured elsewhere.

# Having done "make" to build the executable, issue "./hercules" to make
# libtool create an actual executable.

# You  can  run a test case by "../hyperion/tests/runtest <fname>".  Be
# sure  to  omit  the extension.  Omit the file name or specify '*' (an
# asterisk  enclosed  in  single  quotes)  to  run  all  test that have
# extension .tst.

# Specify  noexit  as  the second argument to suppress the exit command
# that normally terminates the test cases.  This will allow you to poke
# around.

wfn=allTests
dir=../hyperion/tests
fns=${1:-*}
cat $dir/$fns.tst >$wfn.tst
if [ "$2" != "noexit" ] ; then
        echo exit >>$wfn.tst
fi
./hercules -f $dir/tests.conf -r $wfn.tst >$wfn.out 2>&1
sed -n -e '/^HHC01603I \*Testcase/,/^HHC01603I \*Done/p' >$wfn.sout $wfn.out
rexx $dir/redtest.rexx $wfn.sout
